fix：fix a few minor problems
nocobase/nocobase pull request #1008
Opened 2022-11-02 03:39 UTC by baizn

- 修复 plugin 文档中插件的文件名
- samples 中 custom-block 和 hello push 时添加判断，避免热更新时重复添加
- schema-initializer/util 中给 fields 设置默认值，避免页面直接报错

2022-11-02 03:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=1008) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=1008) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: 聚则<br/>:x: baizn<br/><hr/>**聚则** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=1008) it.</sub>

2022-11-03 05:58 UTC, chenos requested changes

2022-11-03 05:58 UTC, chenos commented on docs/en-US/development/your-fisrt-plugin.md
> +查看 `packages/plugins/hello/src/server/index.ts` 文件，并修改为：
index.ts 文件只做 export 导出用的，不写具体代码的

2022-11-03 05:58 UTC, chenos commented on docs/zh-CN/development/your-fisrt-plugin.md
> +查看 `packages/plugins/hello/src/server/index.ts` 文件，并修改为：
index.ts 文件只做 export 导出用的，不写具体代码的

2022-11-03 05:58 UTC, chenos commented on packages/core/client/src/schema-initializer/utils.ts
> +  const { name, fields = [] } = useCollection();
fields 空的情况建议在 useCollection 里完善，这里的 fields 一定是 array

2022-11-03 05:58 UTC, chenos commented on packages/samples/custom-block/src/client/index.tsx
> +  }
这段可以不加的，Client 的 Provider 是 React.memo 包裹的只在第一次初始化的时候渲染（也不允许重复渲染）
SchemaInitializerContext 需要优化，进一步提供更简易的注册区块的 api，如果需要判断重复也在内部处理比较合适，也不用每个插件都写一遍了

2022-11-03 07:06 UTC, baizn commented on packages/samples/custom-block/src/client/index.tsx
> +  }
OK，目前的表现是更新插件内容后，不刷新页面的话就会 push 多次

2022-11-03 07:10 UTC, baizn commented on docs/en-US/development/your-fisrt-plugin.md
> +查看 `packages/plugins/hello/src/server/index.ts` 文件，并修改为：
好的，那sample 和 plugins 里面的就要改下，现在 server 里面的 index.ts 文件内容是
```
export class HelloPlugin extends Plugin {
// 各生命周期定义
}
```

2022-11-03 07:10 UTC, baizn commented on docs/zh-CN/development/your-fisrt-plugin.md
> +查看 `packages/plugins/hello/src/server/index.ts` 文件，并修改为：
同上

2022-11-28 07:05 UTC, closed without merging