feat(workflow): support Http Request Node
nocobase/nocobase pull request #1102
Opened 2022-11-17 13:48 UTC by lyf-coder

2022-11-17 16:09 UTC, mytharcher commented
配置参数中最好增加一个超时配置，通常应该在 5s 以内。

另外考虑到这个节点操作在流程中的表现上实际是“同步”的，有可能拖延流程其他节点的执行，如果有数据操作事务则可能被占用太长时间不释放，在 SQLite 中长时间占用事务会导致并发出现锁库的错误。在考虑网络状况的情况下，超出 1s（相比数据库操作耗时）未返回的请求都可能要改造成停等/恢复的模式。不过这个点可以先记下来，后面再处理。

2022-11-17 16:10 UTC, mytharcher requested changes

2022-11-20 06:51 UTC, lyf-coder commented on packages/plugins/workflow/src/client/components/RequestVarFieldSet.tsx
> +export function RequestVarFieldSet({ calculator, operands = [{ type: '$context', value: '' }], onChange }) {
把可用变量和输入框整合为了 `EjsTextArea`

2022-11-20 06:52 UTC, lyf-coder commented on packages/plugins/workflow/src/client/locale/en-US.ts
> +  'HTTP request url': 'HTTP request url',
已修改

2022-11-20 06:54 UTC, lyf-coder commented on packages/plugins/workflow/src/client/locale/en-US.ts
> +  'Input HTTP request url': 'Input HTTP request url',
进行了修正

2022-11-20 06:54 UTC, lyf-coder commented on packages/plugins/workflow/src/client/locale/en-US.ts
> +  'HTTP request headers': 'HTTP request headers',
已修改

2022-11-20 06:54 UTC, lyf-coder commented on packages/plugins/workflow/src/client/nodes/request.tsx
> +    'variables': {
已修正

2022-11-20 06:56 UTC, lyf-coder commented on packages/plugins/workflow/src/server/instructions/request.ts
> +export interface IRequestConfig {
已修正，url参数直接让拼接到url中(支持变量)，不在额外处理params,只处理data

2022-11-20 06:58 UTC, lyf-coder commented on packages/plugins/workflow/src/server/instructions/request.ts
> +      result: _.isEmpty(input?.result) ? '' : input.result,
暂时保留，提供请求节点后面跟请求节点利用的口子

2022-11-20 06:58 UTC, lyf-coder commented on packages/plugins/workflow/src/server/instructions/request.ts
> +  httpMethod: 'GET' | 'POST';
已支持

2022-11-20 06:59 UTC, lyf-coder commented on packages/plugins/workflow/src/server/instructions/request.ts
> +    switch (httpMethod) {
因为请求的方法与axios的method进行了统一，所以直接使用 axios.request进行请求完成修正

2022-11-20 07:00 UTC, lyf-coder commented on packages/plugins/workflow/src/client/nodes/request.tsx
> +      type: 'object',
不在单独提供params输入参数，而是把URL修改为可使用变量的输入框，直接把参数拼接到url即可

2022-11-20 07:00 UTC, lyf-coder commented on packages/plugins/workflow/src/server/instructions/request.ts
> +    return {
已支持

2022-11-20 07:02 UTC, lyf-coder commented
> 配置参数中最好增加一个超时配置，通常应该在 5s 以内。
> 
> 另外考虑到这个节点操作在流程中的表现上实际是“同步”的，有可能拖延流程其他节点的执行，如果有数据操作事务则可能被占用太长时间不释放，在 SQLite 中长时间占用事务会导致并发出现锁库的错误。在考虑网络状况的情况下，超出 1s（相比数据库操作耗时）未返回的请求都可能要改造成停等/恢复的模式。不过这个点可以先记下来，后面再处理。

已增加超时配置，并进行了saveJob,resume处理。

2022-11-22 04:03 UTC, lyf-coder commented on packages/plugins/workflow/src/server/instructions/request.ts
> +      result: _.isEmpty(input?.result) ? '' : input.result,
已去掉

2022-11-22 10:06 UTC, mytharcher requested changes

2022-11-23 10:28 UTC, mytharcher approved these changes

2022-11-23 10:29 UTC, merged