Fix: plugin-file-manager
nocobase/nocobase pull request #111
Opened 2021-11-27 13:09 UTC by mytharcher

* Simply fixed from test cases.
* Change a little about the env.

2021-11-29 04:35 UTC, chenos requested changes

2021-11-29 04:35 UTC, chenos commented on .env.example
> +API_BASE_PATH=/api/
- API_URL 改成 API_BASE_PATH 不合适，URL 是完整的路径，http://localhost:8000/api/
- API_BASE_PATH 对应的是 API_PREFIX

2021-11-29 04:35 UTC, chenos commented on packages/plugin-collections/src/server.ts
> +        // skipExisting: true,
去掉之后有 BUG，yarn start 会报错

```
TypeError: Cannot read properties of undefined (reading 'field')
[0]     at HasMany._injectAttributes (/Users/chen/nocobase/nocobase-v05/node_modules/sequelize/lib/associations/has-many.js:140:69)
[0]     at Function.hasMany (/Users/chen/nocobase/nocobase-v05/node_modules/sequelize/lib/associations/mixin.js:37:17)
[0]     at Function.Model.associate (/Users/chen/nocobase/nocobase-v05/packages/database/lib/table.ts:335:6)
[0]     at Database.associate (/Users/chen/nocobase/nocobase-v05/packages/database/lib/database.js:367:34)
[0]     at Table.modelInit (/Users/chen/nocobase/nocobase-v05/packages/database/lib/table.ts:376:13)
[0]     at Table.setFields (/Users/chen/nocobase/nocobase-v05/packages/database/lib/table.js:321:10)
[0]     at new Table (/Users/chen/nocobase/nocobase-v05/packages/database/lib/table.ts:246:10)
[0]     at Database.table (/Users/chen/nocobase/nocobase-v05/packages/database/lib/database.ts:463:21)
[0]     at Model.<anonymous> (/Users/chen/nocobase/nocobase-v05/packages/plugin-collections/src/models/collection.ts:74:33)
[0]     at Generator.next (<anonymous>)
```

2021-11-29 04:35 UTC, chenos commented on packages/plugin-file-manager/package.json
> +    "@nocobase/plugin-collections": "^0.5.0-alpha.34",
现在用 workspace 模式之后，可以不用这样了

2021-11-29 04:35 UTC, chenos commented on packages/app/.umirc.ts
> +function getLocalStorageProxy() {
现在有三个 .umirc.ts 文件
`.umirc.ts` 项目根目录下的，用于 demo 运行的
`packages/app/.umirc.ts` app 包下的，app 只用于本地开发调试
`packages/create-nocobase-app/templates/AppGenerator/.umirc.ts` create-nocobase-app 的模板

如果 .umirc.ts 有变动，上面三处位置都要改到

2021-11-30 09:49 UTC, mytharcher commented on .env.example
> +API_BASE_PATH=/api/
这里做了一些修改，增加了几个环境变量：

* API_ORIGIN：生产环境使用的服务器地址，默认为空串（现在没有生产环境）。
* API_ORIGIN_DEV：测试和开发使用的服务器地址，默认为 `http://localhost:13002`（见 .env.example）。
* API_BASE_PATH：服务端路径前缀，默认为 `/api/`。

解决几个问题：

1. 目前前端全部是由 `umi dev` 实时编译提供 web 服务的（开发与测试时），所以前端的 API 访问路径中不需要带主机段，只需要相对路径即可（`/api/xxxx`）。
2. 文件管理插件中的本地服务也需要根据环境进行区分，开发和测试时可以配置为走前端开发服务器的代理访问文件，也可以配置为 API 服务器的主机+端口地址前缀访问。

2021-11-30 09:51 UTC, mytharcher commented on packages/plugin-collections/src/server.ts
> +        // skipExisting: true,
这个问题我这边暂时没发解决，先加回去了。但造成的影响是一旦重启以后，用户动态添加的文件关联字段不会被导入，然后服务器报错。

不知道现阶段有没有其他的 workaround？

2021-12-01 02:18 UTC, chenos requested changes

2021-12-01 02:18 UTC, chenos commented on .umirc.ts
> +function getLocalStorageProxy() {
这部分代码是不是可以提炼一下，放到 @nocobase/utils 里共享？

2021-12-01 02:18 UTC, chenos commented on packages/app/src/apis/index.ts
> +    prefix: process.env.API_BASE_PATH,
所有的 env 要考虑缺失情况的默认值，比如 process.env.API_BASE_PATH || '/api/'

2021-12-01 02:18 UTC, chenos commented on packages/plugin-file-manager/package.json
> +    "@koa/cors": "^3.1.0",
为何有这个？在 server 包里默认就加载了 cors 中间件

2021-12-01 02:18 UTC, chenos commented on packages/plugin-file-manager/src/__tests__/index.ts
> +  app.use(cors({
app 内置 cors 了
```ts
mockServer({
  cors: { origin: '*' }
})
```

2021-12-01 16:17 UTC, chenos commented on packages/utils/src/umiConfig.ts
> +export function getUmiConfig() {
utils 场景下，获取 process.env 需要写在 function 里，不能放在全局（可能 env 都还没载入）

2021-12-01 16:19 UTC, chenos commented on packages/plugin-file-manager/src/storages/local.ts
> +const storages = new Map<string, any>();
插件是共享的，storages 不能放全局

2021-12-02 23:31 UTC, merged