Feat/collection default title
nocobase/nocobase pull request #1122
Opened 2022-11-22 04:05 UTC by lyf-coder

* support config collection title field
* audit-logs support record title

2022-12-16 12:39 UTC, chenos requested changes

2022-12-16 12:39 UTC, chenos commented on packages/plugins/audit-logs/src/server/hooks/after-destroy.ts
> +      const titleField = collection.findField((field) => {
在后端 collection options 里 titleField 放在 collection 里比较合适，不用每次都查 collection.titleField

2022-12-16 12:39 UTC, chenos commented on packages/plugins/audit-logs/src/server/hooks/after-update.ts
> +    const titleField = collection.findField((field) => {
同上

2022-12-16 12:39 UTC, chenos commented on packages/plugins/collection-manager/src/server.ts
> +    this.app.db.on('collections.afterUpdate', async (model: CollectionModel, { context, transaction }) => {
这段加着不合适，时机也不对

2022-12-16 12:39 UTC, chenos commented on packages/plugins/collection-manager/src/server.ts
> +          await this.app.db.getRepository('fields').update({
现在这么处理性能不好，比较建议放到 collection options 里，collection.titleField

2022-12-19 14:04 UTC, lyf-coder commented on packages/plugins/audit-logs/src/server/hooks/after-destroy.ts
> +      const titleField = collection.findField((field) => {
已修改

2022-12-19 14:04 UTC, lyf-coder commented on packages/plugins/audit-logs/src/server/hooks/after-update.ts
> +    const titleField = collection.findField((field) => {
已修改

2022-12-19 14:04 UTC, lyf-coder commented on packages/plugins/collection-manager/src/server.ts
> +    this.app.db.on('collections.afterUpdate', async (model: CollectionModel, { context, transaction }) => {
已去掉

2022-12-19 14:04 UTC, lyf-coder commented on packages/plugins/collection-manager/src/server.ts
> +          await this.app.db.getRepository('fields').update({
已修改

2022-12-29 09:48 UTC, merged