feat: oidc
nocobase/nocobase pull request #1126
Opened 2022-11-22 11:52 UTC by anuoua

2022-11-22 12:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=1126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=1126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=1126) it.</sub>

2022-11-23 12:48 UTC, mytharcher requested changes

2022-11-23 12:48 UTC, mytharcher commented on packages/plugins/oidc/src/server/collections/oidcProviders.ts
> +      name: 'providerName',
名称项与其他表设计保持一致的话一般叫 `title`。

2022-11-23 12:48 UTC, mytharcher commented on packages/plugins/oidc/src/server/collections/oidcProviders.ts
> +      name: 'revodeUrl',
`revokeUrl`

2022-11-23 12:48 UTC, mytharcher commented on packages/plugins/oidc/src/server/collections/oidcProviders.ts
> +      name: 'enable',
一般用形容词性的 `enabled`。

2022-11-23 12:48 UTC, mytharcher commented on packages/plugins/oidc/src/server/actions/getAuthUrl.ts
> +    nonce: provider.clientId,
看了下 openid-client 的官方文档，`nonce` 应该是一个随机数，包里有对应的生成方法：

```ts
import { generators } from 'openid-client';
const nonce = generators.nonce();
```

而不应该是 `provider.clientId`。

2022-11-23 12:48 UTC, mytharcher commented on packages/core/client/src/application/Application.tsx
> +    this.use(SSODataProvider);
这部分代码是不是移到插件里更合适？插件里前端默认导出的组件也可以用于 Provider 嵌套。

2022-11-23 12:48 UTC, mytharcher commented on packages/core/client/src/user/OIDCList.tsx
> +      '__blank',
应该是 `_blank`，多了一个下划线。

2022-11-28 02:28 UTC, anuoua commented on packages/plugins/oidc/src/server/actions/getAuthUrl.ts
> +    nonce: provider.clientId,
这里的 nonce 在登录url中加上，但是跳转的时候不会带回来，在校验的时候又需要用到。
我能想到的是借助外部设施，比如 redis 来存放这个值，否则没办法很好处理。

2022-11-29 15:18 UTC, merged