feat: saml
nocobase/nocobase pull request #1143
Opened 2022-11-24 11:47 UTC by anuoua

2022-11-25 15:25 UTC, mytharcher requested changes

2022-11-25 15:25 UTC, mytharcher commented on packages/core/client/src/user/SigninPage.tsx
> +      <SAMLList />
暂时可以这么写，包括 OIDP 也是，不过之后可能需要重构 users 插件，以提供 IoC 模式的注入结构，否则插件间耦合会比较深。

2022-11-25 15:25 UTC, mytharcher commented on packages/core/client/src/user/SAMLList.tsx
> +  const getSamlList = async () => {
这个方法可以连同调用 `useEffect` 的地方一起重构成一个 hook，包括 `[list, setList]` 也是，主要的组件可以更单纯些。

2022-11-26 01:23 UTC, mytharcher commented on packages/plugins/saml/src/server/plugin.ts
> +    const userPlugin = this.app.getPlugin('users') as UsersPlugin;
和 @chenos 讨论了一下，这个可以先不改，后面等插件管理器完善后正确声明依赖就可以了。

2022-11-29 05:02 UTC, anuoua commented on packages/plugins/saml/src/server/authenticators/saml.ts
> +      'email.$eq': email ?? null,
email 如果没有储存，数据库中为 null，`null !== undefined`，就会查不到。

2022-11-29 09:10 UTC, chenos commented on packages/plugins/saml/src/client/index.tsx
> +    <SigninPageExtensionProvider component={<SAMLList />}>
SAMLList 最好不要在上下文里直接就渲染了，也可能带来性能问题，比较好的方式可以在这里只注册 Component，在具体调用的位置再 render

2022-11-29 15:20 UTC, merged