Feat/snapshot
nocobase/nocobase pull request #1253
Opened 2022-12-16 02:05 UTC by anuoua

2022-12-28 07:47 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +      const fieldDoc = model.get();
从内存里取 https://docs-cn.nocobase.com/api/database/collection#getfield

2022-12-28 07:48 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +        values: fieldDoc,
这里要有个 transaction 参数

2022-12-28 07:49 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +      fieldsHistory.repository.create({
await

2022-12-28 07:50 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +      const collectionDoc = model.toJSON();
这个不完整，用 db.getCollection() 的

2022-12-28 07:50 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +        values: collectionDoc,
transaction

2022-12-28 07:50 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +        records: collectionDoc.fields,
transaction

2022-12-28 07:51 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +      fieldsHistory.repository.createMany({
await

2022-12-28 07:52 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +  async install(options?: InstallOptions) {}
安装时，要初始化所有已存在的 collections 到 history 里

2023-01-01 04:25 UTC, chenos requested changes

2023-01-01 04:25 UTC, chenos commented on packages/plugins/snapshot-field/src/server/collections/collectionsHistory.ts
> +  title: '数据表配置',
title 要改一下

2023-01-01 04:25 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +      const collectionsRepository = this.app.db.getCollection('collections').repository;
用 db.getRepository()
https://docs-cn.nocobase.com/api/database#getrepository

2023-01-01 04:25 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +      }
如果是几百张表，现在这样会很慢的，建议改成
```sql
INSERT INTO table2
SELECT * FROM table1
WHERE condition;
```

2023-01-01 04:25 UTC, chenos commented on packages/plugins/snapshot-field/src/server/plugin.ts
> +        records: collectionDoc.fields,
建表时，可能没有初始化 fields

2023-01-01 04:25 UTC, chenos commented on packages/plugins/snapshot-field/src/client/SnapshotBlock/SnapshotBlockProvider.tsx
> +  const snapshotData = snapshotRecordsubRecord.__parent[association.split('.').pop()];
是否要做缺失判断呢？

2023-01-01 04:25 UTC, chenos commented on packages/core/client/src/collection-manager/CollectionHistoryProvider.tsx
> +export const useHistoryCollectionByKey = (key: string) => {
key 是随机的，用 name 比较好

2023-01-01 04:25 UTC, chenos commented on packages/core/client/src/collection-manager/CollectionHistoryProvider.tsx
> +export const useHistoryCollectionByKey = (key: string) => {
如果做 API 使用，用 collectionName 比较合适

2023-01-02 04:06 UTC, anuoua commented on packages/core/client/src/collection-manager/CollectionHistoryProvider.tsx
> +export const useHistoryCollectionByKey = (key: string) => {
将来colleciotn支持多版本，key能保持唯一，name不行

2023-01-02 04:07 UTC, anuoua commented on packages/plugins/snapshot-field/src/client/SnapshotBlock/SnapshotBlockProvider.tsx
> +  const snapshotData = snapshotRecordsubRecord.__parent[association.split('.').pop()];
目前不需要，这里是点击后才出来的，点击出来的会套上recordProvider

2023-01-04 11:27 UTC, merged