feat: support file collection
nocobase/nocobase pull request #1636
Opened 2023-04-02 07:50 UTC by zhangzhonghe

## Support `File collection`
![image](https://user-images.githubusercontent.com/38434641/229339769-2524edaf-3310-4d60-99eb-019d34eb4df2.png)

2023-04-05 11:55 UTC, chenos commented on packages/core/client/src/collection-manager/interfaces/url.ts
> +      'x-read-pretty': true,
url 是可编辑的

2023-04-05 11:58 UTC, chenos commented on packages/core/client/src/collection-manager/interfaces/url.ts
> +      schema['x-component-props']['size'] = 'small';
这段判断有问题

2023-04-05 11:59 UTC, chenos commented on packages/core/client/src/locale/en_US.ts
> +  "File storage": "File storage",
翻译的放 file-manager 里比较合适

2023-04-05 15:21 UTC, zhangzhonghe commented on packages/core/client/src/collection-manager/interfaces/url.ts
> +      schema['x-component-props']['size'] = 'small';
![image](https://user-images.githubusercontent.com/38434641/230127174-4a8c3e03-26bf-476a-a84f-320561ff1b71.png)
不然没有更好的方法

2023-04-06 03:05 UTC, chenos requested changes

2023-04-06 03:05 UTC, chenos commented on packages/core/client/src/block-provider/hooks/index.ts
> +export const useUploadFiles = () => {
这段代码放插件里比较合适

2023-04-06 03:05 UTC, chenos commented on packages/core/client/src/locale/ja_JP.ts
> +  'Click or drag file to this area to upload': 'クリックまたはドラッグしてファイルをアップロード',
翻译放插件

2023-04-06 03:05 UTC, chenos commented on packages/core/client/src/locale/pt_BR.ts
> +  'Click or drag file to this area to upload': 'Clique ou arraste o arquivo para esta área para fazer o upload',
翻译放插件

2023-04-06 03:05 UTC, chenos commented on packages/core/client/src/schema-initializer/items/UploadActionInitializer.tsx
> +export const UploadActionInitializer = (props) => {
放插件里比较合适

2023-04-06 03:18 UTC, zhangzhonghe commented on packages/core/client/src/locale/ja_JP.ts
> +  'Click or drag file to this area to upload': 'クリックまたはドラッグしてファイルをアップロード',
这些翻译是 Upload.DraggerV2 组件的，该组件比较通用，不适合放在插件吧？

2023-04-06 03:21 UTC, zhangzhonghe commented on packages/core/client/src/block-provider/hooks/index.ts
> +export const useUploadFiles = () => {
OK

2023-04-06 03:21 UTC, zhangzhonghe commented on packages/core/client/src/schema-initializer/items/UploadActionInitializer.tsx
> +export const UploadActionInitializer = (props) => {
OK

2023-04-06 04:43 UTC, merged