feat(plugin-charts): add heatmap chart
nocobase/nocobase pull request #1734
Opened 2023-04-20 08:05 UTC by hellocreep

2023-04-20 08:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=1734) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=1734) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=1734) it.</sub>

2023-04-21 08:03 UTC, chenos requested changes
compileWithKeys 的函数需要改进

2023-04-21 08:03 UTC, chenos commented on packages/plugins/charts/src/client/utils.ts
> +export function compileWithKeys(compiler: typeof Schema['compile']) {
这段代码不严谨，还有 array 的情况是否要处理一下，还有这类工具函数，方便写几个测试用例么？

2023-04-21 08:03 UTC, chenos commented on packages/plugins/charts/src/client/utils.ts
> +      } else if (isObject(source[key])) {
不能用 isObject，这里还包括 array 的，可以用 isPlainObj，isArray 的也要处理

2023-04-22 09:54 UTC, hellocreep commented on packages/plugins/charts/src/client/utils.ts
> +export function compileWithKeys(compiler: typeof Schema['compile']) {
好的没问题

2023-05-06 00:50 UTC, hongboji commented
翻译问题：heatmap 翻译一次中文，提示文字按照官方得修改并翻译英文：2 个「无序名词」或「有序名词」字段
1 个「数值」字段

2023-07-09 00:57 UTC, closed without merging