feat/authentication
nocobase/nocobase pull request #1751
Opened 2023-04-23 09:42 UTC by Xilesun

2023-04-23 09:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=1751) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=1751) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=1751) it.</sub>

2023-04-26 09:14 UTC, chenos requested changes

2023-04-26 09:14 UTC, chenos commented on packages/core/auth/src/auth-manager.ts
> +    this.app.resourcer.registerActions(actions);
这里是定义 resource
```ts
this.app.resourcer.define({name: 'auth', actions});
```

2023-04-26 09:14 UTC, chenos commented on packages/core/auth/src/base/auth.ts
> +  }
这个叫 getUser 比较不容易困惑

2023-04-26 09:14 UTC, chenos commented on packages/plugins/users/src/collections/authenticators.ts
> +      uiSchema: {
这种系统表的，可以不用配 uiSchema 的

2023-04-26 09:14 UTC, chenos commented on packages/plugins/users/src/collections/user-auth-infomation.ts
> +  name: 'userAuthInfomation',
按现在表名的命名规则，中间表叫 `usersAuthenticators` 比较合适

2023-04-26 09:14 UTC, chenos commented on packages/core/auth/src/auth.ts
> +  signUp: () => Promise<any>;
这些 IAuth 里已经定义了吧？

2023-04-26 09:36 UTC, Xilesun commented on packages/core/auth/src/auth.ts
> +  signUp: () => Promise<any>;
这里implement IAuth，里面不写会报错的。另外分abstract和非abstract，是extend的时候一定要有`check`和`getIdentity`，而`signIn`, `signUp`, `signOut`是可选的，比如api认证方式不需要。

2023-04-26 09:38 UTC, Xilesun commented on packages/core/auth/src/base/auth.ts
> +  }
这个是Auth定义了`getIdentity`，这个命名是考虑api认证和user认证都需要获取某个身份，即`getIdentity`，需要的话可以在`BaseAuth`加个方法
```
async getUser() {
   return await this.getIdentity();
}
```
这样可能好一些。

2023-04-26 09:39 UTC, Xilesun commented on packages/plugins/users/src/collections/authenticators.ts
> +      uiSchema: {
Ok，这块collection是上一版写的，还没改，后面挪到`plugin-auth`会重新设计，下同。

2023-05-05 11:51 UTC, closed without merging

2023-05-05 11:53 UTC, Xilesun commented
#1804