feat(core client Marddown): markdown support tempalt with handlebars in detail
nocobase/nocobase pull request #1776
Opened 2023-04-27 03:41 UTC by mdumu

You can use all the syntax of handlebars
[https://handlebarsjs.com/](https://handlebarsjs.com/)
![image](https://user-images.githubusercontent.com/26764888/234753723-e3cd0324-4c68-48c9-afcb-ab9f60f1b2c1.png)
![image](https://user-images.githubusercontent.com/26764888/234753750-5891ed8d-96ac-4b8c-944d-88a089358886.png)

2023-04-27 03:45 UTC, mdumu commented
原本想使用动态变量组件实现，发现对nocobase组件这块理解不到位，加上不支持很多模版语法，就直接手写template吧

2023-05-05 02:54 UTC, mytharcher commented
如果只是在 Markdown 区块上扩展 handlebars 模板语法的话，有一定局限性，且增加了 Markdown 区块的复杂度。这块需求建议单独扩展成一个“模板区块”的插件，用于不同模板引擎进行区块内容渲染。也可以扩展成多个模板引擎区块的插件，比如 plugin-mustache-block/plugin-handlebars-block/plugin-ejs-block 等，方便使用者选择。

2023-05-05 03:08 UTC, mytharcher requested changes
如果只是在 Markdown 区块上扩展 handlebars 模板语法的话，有一定局限性，且增加了 Markdown 区块的复杂度。这块需求建议单独扩展成一个“模板区块”的插件，用于不同模板引擎进行区块内容渲染。也可以扩展成多个模板引擎区块的插件，比如 plugin-mustache-block/plugin-handlebars-block/plugin-ejs-block 等，方便使用者选择。

2023-05-06 02:24 UTC, mdumu commented
> 如果只是在 Markdown 区块上扩展 handlebars 模板语法的话，有一定局限性，且增加了 Markdown 区块的复杂度。这块需求建议单独扩展成一个“模板区块”的插件，用于不同模板引擎进行区块内容渲染。也可以扩展成多个模板引擎区块的插件，比如 plugin-mustache-block/plugin-handlebars-block/plugin-ejs-block 等，方便使用者选择。

对nocobase前端插件开发机制不太熟，尝试了一下，有点无从下手😅。方便的话，可以官方实现一下么

2023-05-06 02:31 UTC, mytharcher commented
> 对nocobase前端插件开发机制不太熟，尝试了一下，有点无从下手😅。方便的话，可以官方实现一下么

目前这块可能优先级暂时不高，如需求比较强烈，可以使用自行 fork 的版本，但当前 PR 的修改不会被合并。如需进一步了解插件开发，可以参考现有的文档： https://docs-cn.nocobase.com/development 。

2023-05-26 07:47 UTC, closed without merging