fix: `yarn nocobase upgrade` consuming a lot of time.
nocobase/nocobase pull request #1835
Opened 2023-05-10 13:35 UTC by icezohu

fix: removed unwanted logic comsuming a lot of time when doing `yarn nocobase upgrade`
with feat: implement db snapshots for checking models that should be synced to db. which is doing more to improve the upgrade processing.

2023-05-10 13:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=1835) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=1835) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=1835) it.</sub>

2023-05-14 08:39 UTC, chareice requested changes

2023-05-14 08:39 UTC, chareice commented on packages/core/database/src/snapshot.ts
> +  const snapshotDir = path.join('storage', 'db', 'snapshots', database.options.dialect || 'default', database.options.schema || 'public');
重复逻辑需要封装，另外需要跑prettier格式化代码

2023-05-14 08:39 UTC, chareice commented on packages/core/server/src/application.ts
> +    // await this.db.sync({
注释代码可移除

2023-05-14 08:39 UTC, chareice commented on packages/core/database/src/collection.ts
> +    this.model.afterDestroy((instance, options) => {
这个Hook的含义如何理解，是model有记录从数据库删除就调用deleteSnapshot吗？

2023-05-14 08:39 UTC, chareice commented on packages/core/database/src/model.ts
> +    saveSnapshot(this.database, this);
建议Snapshot相关逻辑封装入一个类中

2023-05-14 16:21 UTC, icezohu commented on packages/core/database/src/snapshot.ts
> +  const snapshotDir = path.join('storage', 'db', 'snapshots', database.options.dialect || 'default', database.options.schema || 'public');
优化：已放到类里面，每个数据库路径仅初始化一次。已改用prettier格式化代码。

2023-05-14 16:21 UTC, icezohu commented on packages/core/server/src/application.ts
> +    // await this.db.sync({
优化：注释代码已移除

2023-05-14 16:26 UTC, icezohu commented on packages/core/database/src/collection.ts
> +    this.model.afterDestroy((instance, options) => {
优化：Hook 方法已删除。这里是误解了 model 的 afterDestroy，以为是删除表单的时候触发。没有仔细测试这段逻辑，不够严谨。

2023-05-14 16:33 UTC, icezohu commented on packages/core/database/src/model.ts
> +    saveSnapshot(this.database, this);
优化：已封装为 DatabaseSnapshot 类，因属于 database 级别，已放在 Database 类中作为属性实例化。

2023-05-15 00:43 UTC, chareice requested changes

2023-05-15 00:43 UTC, chareice commented on packages/core/database/src/model.ts
> +    // @ts-ignore
此处不需要ts-ignore

2023-05-15 00:43 UTC, chareice commented on packages/core/database/src/model.ts
> +    let modelResult = await SequelizeModel.sync.call(this, options);
这里可以用const

2023-05-15 00:43 UTC, chareice commented on packages/core/database/src/snapshot.ts
> +  validateSnapshot(model: ModelStatic<Model>, options) {
1. 现在 snapshot 相关的方法都封装在类中了，类内部的函数名可以移除掉snapshot，比如可以直接是 this.database.snapshot.save()；
2. 这里叫 validate 有些不太匹配，可以叫类似 `hasChanged` 更好理解

2023-05-15 00:43 UTC, chareice commented on packages/core/database/src/snapshot.ts
> +    const snapshotFile = path.join(this.snapshotDir, `${model.tableName}.json`);
获取snapShotFild路径需要在类内部封装成一个方法，这个逻辑与save中有重复代码

2023-05-15 00:43 UTC, chareice commented on packages/core/database/src/snapshot.ts
> +    let snapshot = {
获取model的snapshot也需要封装成一个方法，如果这边逻辑有变化现在需要改动多处

2023-05-15 02:39 UTC, icezohu commented on packages/core/database/src/model.ts
> +    // @ts-ignore
优化：已移除，遗留代码，抱歉。

2023-05-15 02:39 UTC, icezohu commented on packages/core/database/src/model.ts
> +    let modelResult = await SequelizeModel.sync.call(this, options);
优化：已改正。

2023-05-15 02:41 UTC, icezohu commented on packages/core/database/src/snapshot.ts
> +  validateSnapshot(model: ModelStatic<Model>, options) {
优化：snapshot 所有方法已简化命名。谢谢改名，很好理解。

2023-05-15 02:46 UTC, icezohu commented on packages/core/database/src/snapshot.ts
> +    const snapshotFile = path.join(this.snapshotDir, `${model.tableName}.json`);
优化：已封装 snapshotFilePath 方法。

2023-05-15 02:46 UTC, icezohu commented on packages/core/database/src/snapshot.ts
> +    let snapshot = {
优化：已封装 snapshotFromModel 方法。

2023-09-08 08:17 UTC, closed without merging