feat: mutex-manager
nocobase/nocobase pull request #2044
Opened 2023-06-13 08:41 UTC by icezohu

with async-mutex by default
with redis-mutex when REDIS_MUTEX is on
with other mutex when registered and called with relative option 
test: mutex-manager.test with sequence field and sort field

by Jacob

> **Note**
> This is a template for submitting a new feature. Use the bug fix template if you're submitting a bug fix pull request by adding `template=bug_fix.md` to your pull request URL.

# Description (需求描述)
Describe the new feature or modification to an existing feature clearly and consciously.

# Motivation (需求背景)
Explain the reason for adding or modifying this feature.

# Key changes (关键改动）
Provide a technically detailed description of the key changes made.
- Frontend (前端)
- Backend (后端)

# Test plan (测试计划)
## Suggestions (测试建议)
Provide any suggestions or recommendations for improvements in the testing plan.

## Underlying risk (潜在风险)
Identify any potential risks or issues that may arise from the new feature or modification.

# Showcase (结果展示）
Including any screenshots of the new feature or modification.

2023-06-17 10:30 UTC, chenos requested changes

2023-06-17 10:30 UTC, chenos commented on packages/core/utils/src/mutex-manager/mutex-manager.ts
> +  public setupEventListeners(app: any) {
这个设计很奇怪，理想情况不应该依赖 App 相关模块

2023-06-17 10:30 UTC, chenos commented on packages/core/server/package.json
> +    "async-mutex": "^0.3.2"
这些依赖的声明也不适合放在这里

2023-06-17 10:37 UTC, icezohu commented on packages/core/utils/src/mutex-manager/mutex-manager.ts
> +  public setupEventListeners(app: any) {
这个是为了单元测试的时候，能够断开redis的连接，不然测试任务结束不了。我再看看有没有别的办法。

2023-06-18 06:17 UTC, icezohu commented on packages/core/database/src/fields/sort-field.ts
> +      db_dialect: this.database.options.dialect,
已修正

2023-06-18 06:17 UTC, icezohu commented on packages/core/utils/src/index.ts
> +export * from './mutex-manager';
已重构

2023-06-18 06:17 UTC, icezohu commented on packages/core/utils/src/mutex-manager/mutex-manager.ts
> +  action?: string;
已修正

2023-06-18 06:17 UTC, icezohu commented on packages/core/server/package.json
> +    "async-mutex": "^0.3.2"
已修正

2023-06-18 11:59 UTC, icezohu commented on packages/core/utils/src/mutex-manager/mutex-manager.ts
> +  public setupEventListeners(app: any) {
删除了相关代码之后，有9个测试用例出错，大部分报 `ExecutionError: The operation was unable to achieve a quorum during its retry window.`

2023-09-08 08:20 UTC, closed without merging