refactor: 重构 application、router、plugin
nocobase/nocobase pull request #2068
Opened 2023-06-18 01:40 UTC by dream2023

> **Note**
> This is a template for submitting a new feature. Use the bug fix template if you're submitting a bug fix pull request by adding `template=bug_fix.md` to your pull request URL.

# Description (需求描述)
Describe the new feature or modification to an existing feature clearly and consciously.

# Motivation (需求背景)
Explain the reason for adding or modifying this feature.

# Key changes (关键改动）
Provide a technically detailed description of the key changes made.
- Frontend (前端)
- Backend (后端)

# Test plan (测试计划)
## Suggestions (测试建议)
Provide any suggestions or recommendations for improvements in the testing plan.

## Underlying risk (潜在风险)
Identify any potential risks or issues that may arise from the new feature or modification.

# Showcase (结果展示）
Including any screenshots of the new feature or modification.

2023-06-22 06:51 UTC, dream2023 commented on packages/core/client/src/application-v2/Application.tsx
> +  addProviders(providers: (ComponentType | [ComponentType, any])[]) {
Application 中 `registerComponent`、`registerScope` 等改为了 `addXX`。 

更改原因：现在是 addXX 和 registerXX 混用，处于简单考虑所以统一改为 `addXX`，当然也可以统一改为 `registerXX`。

2023-06-22 06:51 UTC, dream2023 commented on packages/plugins/mobile-client/src/client/router/InterfaceRouter.tsx
> +    const router = new Router({ type: 'hash' }, app);
嵌套 Router 采用单独 `new  Router()` 的方式实现。

原因：之所以没有在 `Application` 那边处理，主要是这个场景十分特殊，一般插件不会这样搞，如果在 Application 那边增加逻辑，会让核心逻辑过于不干净。

2023-06-22 06:51 UTC, dream2023 commented on packages/app/client/src/pages/index.tsx
> +    headers: {
这里把 `apiClient` 的 `baseURL` 和 `headers`  从内核中移到这里来，为了更加纯粹的内核。

如果不这样写，一方面主体应用必须提供 `process.env.API_BASE_URL` 这个环境变量的替换，另一方面 `X-Hostname` 和 `X-Timezone` 也不应该是必须的头。

2023-06-22 06:51 UTC, dream2023 commented on packages/core/client/src/schema-component/core/SchemaComponentOptions.tsx
> +  const components = { ...app.components, ...options.components, ...props.components };
其实 `MainComponent` 上面注入了 `SchemaComponentOptions`，但是不知道为什么 `useSchemaOptionsContext` 获取不到，所以这里使用了 `useApp()` 将顶部注入的在这里用扩展运算符合并。

2023-06-26 11:34 UTC, chenos requested changes

2023-06-26 11:34 UTC, chenos commented on packages/core/client/src/application-v2/RouterManager.tsx
> +  createRouter() {
这个是返回 Router 组件，叫 `getRouterComponent()` 更合适一些

2023-06-26 11:34 UTC, chenos commented on packages/core/client/src/application-v2/Application.tsx
> +    this.router = new RouterManager(options.router, this);
RouterManager 可以考虑把 app 的依赖去掉，改成这样

```ts
const router = new RouterManager({
  renderComponent,
});
```

function 的用法
```ts
const router = createRouterManger({
  renderComponent,
})
```

2023-06-26 11:34 UTC, chenos commented on packages/core/client/src/application-v2/RouterManager.tsx
> +            element: Component ? this.app.renderComponent(Component) : item.element,
RouterManager 可以考虑把 app 的依赖去掉，改成这样

```ts
const router = new RouterManager({
  renderComponent,
});
```

function 的用法
```ts
const router = createRouterManger({
  renderComponent,
})
```

2023-06-26 11:41 UTC, chenos commented on packages/core/client/src/application-v2/Application.tsx
> +    this.router = new RouterManager(options.router, this);
提供 createRouterManger 方法，插件里扩展自己的 router 也更方便

2023-06-26 15:15 UTC, chenos commented on packages/plugins/mobile-client/src/client/router/InterfaceRouter.tsx
> +    const router = new RouterManager({ type: 'hash' }, app);
从扩展性来说，mobileRouter 放到 plugin 那里定义比较好

```ts
export class MobileClientPlugin extends Plugin {
  public mobileRouter: RouterManager;
  async load() {
    this.mobileRouter = createRouterManager({ type: 'hash' });
  }
}
```

2023-06-26 15:19 UTC, chenos commented on packages/core/client/src/application-v2/PluginManager.ts
> +  protected pluginInstances: Plugin[] = [];
插件的实例是 Map 类型的 `Map<string, Plugin>`，其他插件可能需要取 plugin 实例的，比如

```ts
const plugin = pm.get('acl');
```

2023-06-27 01:18 UTC, dream2023 commented on packages/app/client/src/pages/index.tsx
> +  plugins: [NocoBaseClientPresetPlugin],
OK

2023-06-27 01:18 UTC, dream2023 commented on packages/core/client/src/application-v2/Application.tsx
> +  renderProviders() {
OK

2023-06-27 01:19 UTC, dream2023 commented on packages/core/client/src/application-v2/Application.tsx
> +    this.router = new RouterManager(options.router, this);
OK

2023-06-27 01:34 UTC, dream2023 commented on packages/core/client/src/application-v2/Application.tsx
> +    this.router = new RouterManager(options.router, this);
这里的 `renderComponent` 是必选还是可选？

2023-06-27 01:50 UTC, dream2023 commented on packages/core/client/src/application-v2/PluginManager.ts
> +  async add<T = any>(plugin: typeof Plugin, opts?: T) {
直接读 `Plugin.name` 是否可以，不需要传，但是上面的 `usePlugin` 改为 `getPluginInstance` 传入的是 Class 的 name。

我的想法是能不需要传的东西就不传

```ts
class FooPlugin extends Plugin {}

app.pm.add(FooPlugin)

app.pm.getInstance('FooPlugin') 
app.pm.getInstance('Foo') 
app.pm.getInstance('foo') 
```

2023-06-27 05:56 UTC, chenos commented on packages/core/client/src/application-v2/Application.tsx
> +    this.router = new RouterManager(options.router, this);
可选

2023-06-27 14:05 UTC, chenos commented on packages/presets/nocobase/src/client/index.ts
> +      const ProviderComponent = await import(`./plugins/${pluginName}`);
preset 内置的 plugins 目录放到这里是 OK 的，第三方插件没办法这里

2023-06-27 14:10 UTC, chenos commented on packages/core/client/src/schema-component/core/SchemaComponentOptions.tsx
> +  const app = useApp();
useApp 放这里不合适，app 的 components 最终是传给 SchemaComponentProvider 的，按现在放 SchemaComponentPlugin 里合适一些

```ts
class SchemaComponentPlugin extends Plugin {
  async load() {
    this.addComponents();
    this.app.use(SchemaComponentProvider, { components: this.app.components, scope: this.app.scopes });
  }
}
```

2023-06-27 14:10 UTC, chenos commented on packages/core/client/src/schema-component/core/index.tsx
> +    this.app.use(SchemaComponentProvider);
app 的 components 和 scope 是注册到这里的
```ts
this.app.use(SchemaComponentProvider, { components: this.app.components, scope: this.app.scopes });
```

2023-06-28 01:20 UTC, dream2023 commented on packages/presets/nocobase/src/client/index.ts
> +      const ProviderComponent = await import(`./plugins/${pluginName}`);
不太明白什么意思，第三方插件也不需要放这里，如果是静态的放到项目 `new Application({ plugins: [xxx] })` 那里，如果是动态的，等待动态功能就行了。

2023-07-07 06:35 UTC, merged