Add *.pdf preview
nocobase/nocobase pull request #2105
Opened 2023-06-23 09:49 UTC by DiFly

> **Note**
> Add *.pdf preview in modal iframe

# Description (需求描述)
Added the functionality of previewing *.pdf files by clicking on the file icon in the table or list. 

# Motivation (需求背景)
We need a convenient preview of *.pdf files without downloading to a local PC.

# Key changes (关键改动）
This is implemented by creating a simple modal window with an iframe (the source of which is a link to the *.pdf file). Additional libraries are not used.

## Underlying risk (潜在风险)
If the browser does not support native viewing of *.pdf files, the file will not be viewed.

# Showcase (结果展示）
Screenshots of the new feature.
![Screenshot_1](https://github.com/nocobase/nocobase/assets/16261891/4e12ca7a-a1ef-4ce1-b7c9-e26c5146772a)
![Screenshot_2](https://github.com/nocobase/nocobase/assets/16261891/4486e6b0-a37c-4dba-8b1b-1a555b9a5a60)

2023-06-23 09:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=2105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=2105) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: alexkash<br/>:x: DiFly<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=2105) it.</sub>

2023-06-25 04:11 UTC, dream2023 requested changes

2023-06-25 04:11 UTC, dream2023 commented on packages/core/client/src/schema-component/antd/upload/shared.ts
> +  return reg.test(extName);
`extName.toLowerCase().endsWith('.pdf')` is better.

2023-06-25 04:11 UTC, dream2023 commented on packages/core/client/src/schema-component/antd/upload/ReadPretty.tsx
> +  const [visiblePDF, setVisiblePDF] = useState(false);
```ts
const [fileType, setFileType] = useState<'image' | 'pdf'>();
```

2023-06-25 04:11 UTC, dream2023 commented on packages/core/client/src/schema-component/antd/upload/ReadPretty.tsx
>    const [photoIndex, setPhotoIndex] = useState(0);
```ts
const [fileIndex, setFileIndex] = useState(0);
```

2023-06-25 04:11 UTC, dream2023 commented on packages/core/client/src/schema-component/antd/upload/ReadPretty.tsx
>                  setPhotoIndex(index);
```ts
setVisible(true);
setFileIndex(index);
setFileType('image')
```

2023-06-25 04:11 UTC, dream2023 commented on packages/core/client/src/schema-component/antd/upload/ReadPretty.tsx
> +                setPhotoIndex(index);
```ts
setVisible(true);
setFileIndex(index);
setFileType('pdf')
```

2023-06-25 04:11 UTC, dream2023 commented on packages/core/client/src/schema-component/antd/upload/ReadPretty.tsx
> +      {visiblePDF && (
```tsx
visible && fileType === 'pdf' && 
```

2023-06-25 04:11 UTC, dream2023 commented on packages/core/client/src/schema-component/antd/upload/ReadPretty.tsx
> +          }} >
Replace by [modal](https://4x.ant.design/components/modal/) Component

2023-06-25 07:52 UTC, dream2023 requested changes

2023-06-25 07:52 UTC, dream2023 commented on packages/core/client/src/schema-component/antd/upload/Upload.tsx
> +                Download
```ts
const { t } = useTranslation();
t('download')
t('close')
```

2023-06-26 15:05 UTC, DiFly commented
Refactoring done, are there any more changes to make?

2023-06-27 08:00 UTC, merged