feat(plugin-api-keys): support fetch api via api-keys
nocobase/nocobase pull request #2111
Opened 2023-06-24 09:57 UTC by Dunqing

> **Note**
> This is a template for submitting a new feature. Use the bug fix template if you're submitting a bug fix pull request by adding `template=bug_fix.md` to your pull request URL.

# Description (需求描述)
Describe the new feature or modification to an existing feature clearly and consciously.

创建一个 api key 用于请求 nocobase 内部接口

# Motivation (需求背景)
Explain the reason for adding or modifying this feature.

# Key changes (关键改动）
Provide a technically detailed description of the key changes made.
- Frontend (前端)
- Backend (后端)

# Test plan (测试计划)
## Suggestions (测试建议)
Provide any suggestions or recommendations for improvements in the testing plan.

## Underlying risk (潜在风险)
Identify any potential risks or issues that may arise from the new feature or modification.

# Showcase (结果展示）
Including any screenshots of the new feature or modification.

2023-06-26 02:12 UTC, Xilesun requested changes
用户只能管理自己的keys，管理界面需要按用户过滤，删除的接口需要判断key是否属于当前用户。

2023-06-27 08:06 UTC, chenos commented on packages/core/acl/src/acl.ts
> +          }
判断 role 的代码位置看起来不对

2023-06-27 08:11 UTC, chenos commented on packages/core/auth/src/base/auth.ts
> +      };
auth 里有 this.ctx.state 的

2023-06-27 08:12 UTC, chenos commented on packages/core/auth/src/base/auth.ts
> +  async signIn(payload: any) {
any 具体一点比较好

2023-06-27 08:13 UTC, Dunqing commented on packages/core/acl/src/acl.ts
> +          }
在这里的原因是因为有些接口是只需要登录了就能访问的，如果在 setCurrentRole 里会有问题

2023-06-27 08:17 UTC, chenos commented on packages/plugins/acl/src/middlewares/setCurrentRole.ts
> +  ctx.state.currentRole = roles.find((role) => role.name === currentRole)?.name;
如果指定了 currentRole，查到的 currentRole，没有报错
如果没有指定 currentRole，按用户默认的来

2023-06-27 08:27 UTC, chenos requested changes

2023-06-27 08:27 UTC, chenos commented on packages/core/auth/src/base/auth.ts
> +    user.setDataValue('roles', roles);
这里是没必要返回用户所有 roles，这段代码放这里看着不太合理

2023-06-27 08:27 UTC, chenos commented on packages/core/sdk/src/APIClient.ts
> +    }
signIn 时，由后端返回 currentRole，不应该在前端来处理这个

2023-06-27 08:27 UTC, chenos commented on packages/core/acl/src/acl.ts
> +          }
是因为现在 setCurrentRole 的逻辑不太对

2023-06-27 08:27 UTC, chenos commented on packages/core/auth/src/base/auth.ts
> +    user.setDataValue('roles', roles);
signIn 的接口除了 user token 以外，还需要 currentRole，这个 currentRole 怎么加进来，得再想想，这里是 core 的，写这段代码看起来有点奇怪

2023-06-27 08:31 UTC, Dunqing commented on packages/core/auth/src/base/auth.ts
> +    user.setDataValue('roles', roles);
还原了，现在没有 X-Role 用 default 能解决这个问题

2023-06-27 08:31 UTC, Dunqing commented on packages/core/sdk/src/APIClient.ts
> +    }
revert 了

2023-06-27 08:32 UTC, Dunqing commented on packages/plugins/acl/src/middlewares/setCurrentRole.ts
> +  ctx.state.currentRole = roles.find((role) => role.name === currentRole)?.name;
改好了，这里改好 signIn 就不需要 roles 了

2023-06-27 08:49 UTC, closed without merging

2023-06-27 08:56 UTC, chenos requested changes

2023-06-27 08:56 UTC, chenos commented on packages/core/auth/src/auth.ts
> +  async signOut(...args: any[]): Promise<any> {}
这里的 args 是啥，用 any 会看不懂

2023-06-27 08:56 UTC, chenos commented on packages/core/auth/src/base/auth.ts
> +  async signIn(payload: SignPayload) {
signIn 这里提供 SignPayload 看起来不太对，比较好的做法应该是这样：
```ts
ctx.auth.jwt.sign(payload, options);
```

2023-06-27 08:56 UTC, chenos commented on packages/plugins/api-keys/src/server/api-keys-auth.ts
> +export class ApiKeysAuth extends BaseAuth {
ApiKeysAuth 有点多余，这里只需要 jwt 复用就行

2023-06-27 08:56 UTC, chenos commented on packages/core/auth/src/base/jwt-service.ts
> +  sign(payload: SignPayload) {
```ts
sign(payload, options) {
  return jwt.sign(payload, this.secret(), { expiresIn: this.expiresIn(), ...options });
}
```

2023-06-27 08:56 UTC, chenos commented on packages/plugins/api-keys/src/server/actions/api-keys.ts
> +  const apiKeysAuth = new ApiKeysAuth({
这里比较好的方式是直接调用 auth.jwt
```ts
ctx.auth.jwt.sign({ userId, roleName }, { expiresIn });
```

2023-06-27 08:56 UTC, chenos commented on packages/plugins/api-keys/src/server/actions/api-keys.ts
> +  ctx.action.params.filter = { $and: [{ createdBy: { id: { $eq: ctx.auth.user.id } } }] };
用 `ctx.action.mergeParams`，写在 app.resourcer.use() 里比较好

```ts
ctx.action.mergeParams({
  filter: { createdBy: { id: { $eq: ctx.auth.user.id } },
});
```