add action log tempalte
nocobase/nocobase pull request #239
Opened 2022-03-13 12:24 UTC by semmywong

add action log tempalte

2022-03-14 16:18 UTC, semmywong commented
refactor action log

2022-03-15 02:07 UTC, chenos requested changes

2022-03-15 02:07 UTC, chenos commented on packages/client/src/action-logs/ActionLog.tsx
> +  initializers.BlockInitializers.items.push({
放在这里处理不太好

2022-03-15 02:07 UTC, chenos commented on packages/client/src/action-logs/ActionLog.tsx
> +  const schema = createSchema();
useMemo 处理一下比较好，要不每次都会 create 一下

2022-03-28 07:38 UTC, merged