chore: using vitest for backend code testing instead of jest
nocobase/nocobase pull request #3163
Opened 2023-12-08 06:50 UTC by chareice

2023-12-08 15:11 UTC, Dunqing requested changes

2023-12-08 15:11 UTC, Dunqing commented on scripts/vitest-node.setup.ts
vitest 应该会自动读 `.env.test`

2023-12-09 08:17 UTC, chareice commented on scripts/vitest-node.setup.ts
试了好像不太行，去掉setup读不到.env.test

2023-12-09 08:21 UTC, Dunqing commented on scripts/vitest-node.setup.ts
如果没改 NODE_ENV 的话那应该就是 bug 了

2023-12-13 06:27 UTC, closed without merging