chore: data source api
nocobase/nocobase pull request #4588
Opened 2024-06-07 03:09 UTC by chareice

2024-06-13 12:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=4588) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=4588) before we can accept your contribution.<br/>**0** out of **4** committers have signed the CLA.<br/><br/>:x: katherinehhh<br/>:x: 2013xile<br/>:x: chenos<br/>:x: chareice<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=4588) it.</sub>

2024-07-19 05:46 UTC, chenos requested changes

2024-07-19 05:46 UTC, chenos commented on packages/core/client/src/schema-initializer/buttons/RecordBlockInitializers.tsx
> +        const collection = useCollection() || ({} as any);
这里还漏了一处

2024-07-19 05:46 UTC, chenos commented on packages/core/client/src/schema-component/antd/input/ReadPretty.tsx
> +        {props.value && typeof props.value === 'object' ? JSON.stringify(props.value) : compile(props.value)}
null的看起来没处理？

2024-07-19 05:54 UTC, katherinehhh commented on packages/core/client/src/schema-initializer/buttons/RecordBlockInitializers.tsx
> +        const collection = useCollection() || ({} as any);
好的，加上了

2024-07-19 14:26 UTC, merged