feat(plugin-workflow): add date range options to system variable in workflow plugin
nocobase/nocobase pull request #4728
Opened 2024-06-22 06:21 UTC by huanghui1

# Description

# Motivation

# Key changes

- Frontend
- Backend

# Test plan
## Suggestions

## Underlying risk

# Showcase

2024-06-22 06:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=4728) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=4728) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=4728) it.</sub>

2024-06-23 04:28 UTC, mytharcher requested changes
还需要增加相关的单元测试，例如：

```
    it('params.filter on date range: yesterday', async () => {
      const n1 = await workflow.createNode({
        type: 'query',
        config: {
          collection: 'posts',
          params: {
            filter: {
              createdAt: {
                $dateOn: '{{$system.dateRange.yesterday}}',
              },
            },
          },
        },
      });

      const now = new Date();
      const yesterday = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1);

      const post = await PostRepo.create({
        values: {
          title: 't1',
          createdAt: yesterday
        },
      });

      await sleep(500);

      const [execution] = await workflow.getExecutions();
      const [job] = await execution.getJobs();
      expect(job.result.title).toBe(post.title);
    });
```

不一定套在 query 节点里，只要能测试 `Processor.getParsedValue` 或者 `Processor.getScope` 的解析结果正确，且可以作为 filter 参数交给 `repository.find` 方法查询出正确的结果即可（时间边界范围需要覆盖）。

可以考虑单独针对 functions 开一个单测文件。

2024-06-23 04:28 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-workflow/src/client/variable.tsx
> +              key: 'dateTime',
key 和 value 保持一致。

2024-06-23 04:28 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-workflow/src/server/Plugin.ts
> +  functions: Registry<CustomFunction | Map<string, CustomFunction>> = new Registry();
这个类型可以不修改，key 使用点号分隔的字符串也 ok，类型上简单一些。

2024-06-23 04:28 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-workflow/src/server/Processor.ts
> +    const systemFns = bindScope(this.options.plugin.functions.getEntities());
如果用点号分隔的 key path，systemFns 也可以直接用 path 拼，比如 `lodash.set(systemFns, path, functions[path])`。

2024-06-23 04:28 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-workflow/src/server/functions/index.ts
> +    const yd = getDayRange({ now: new Date(), offset: -2, timezone: '+08:00' });
对一个单位的时间范围要换成：

```
utc2unit({ now: new Date(), unit: 'day', offset: -1, timezone: '+08:00' });
```

这种写法。

另外由于本期不考虑改进工作流的时区配置，时区需要改成系统时区，不能写死，比如通过 `new Date().getTimezoneOffset()` 计算出来。

2024-06-24 12:26 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-workflow/src/server/functions/index.ts
> +    const start = dayjs().subtract(1, 'w').startOf('w');
这些地方都可以直接用 utils 里的方法，可以继续看下 `utc2unit` 的调用方法。不用再用 dayjs 算一遍。

2024-06-25 14:51 UTC, mytharcher requested changes

2024-06-27 13:16 UTC, mytharcher requested changes
核心问题是测试用例的写法需要简化，可以参考这条评论：

> 可以直接使用 parse 后的内容对某个 repository 的 findAll 进行测试，会简化很多。

时间值的设置需要考虑临界点，更有针对性。

2024-06-27 13:16 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/function.test.ts
> +      const posts = await PostRepo.createMany({
这样写会每行记录触发一次工作流，导致后面的执行计划是多个，可能会互相干扰。

2024-06-27 13:16 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/function.test.ts
> +const nextYearLastDay = nextYear.clone().endOf('year');
这些变量可以放在 beforeEach 周期里进行初始化，以避免小概率 case 延迟执行刚好在跨天临界点时造成的错误。

2024-06-27 13:16 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/function.test.ts
> +          { title: 'today', updatedAt: today.toDate() },
考虑临界点的时间，比如测 today，那么只有这 24 小时内的时间点才应该被筛选，往前 1 秒钟，往后第二天 0 点的时间作为测试字段的值更容易检查是否有时区问题。

2024-06-29 09:10 UTC, huanghui1 commented on packages/plugins/@nocobase/plugin-workflow/src/server/__tests__/function.test.ts
> +          { title: 'today', updatedAt: today.toDate() },
> 考虑临界点的时间，比如测 today，那么只有这 24 小时内的时间点才应该被筛选，往前 1 秒钟，往后第二天 0 点的时间作为测试字段的值更容易检查是否有时区问题。

Hi, 这个地方parse出来的值类似于2024-06-28+08:00这样，貌似不能往这上面加上1秒钟

2024-06-30 08:23 UTC, mytharcher approved these changes

2024-06-30 08:30 UTC, merged