Improve collection tree implementation
nocobase/nocobase pull request #4770
Opened 2024-06-27 10:05 UTC by jimmy201602

# Description
Improve collection tree implementation

# Motivation
The idea is taken from the Linux root file system.

# Key changes
- Frontend
- Backend

# Test plan
## Suggestions

## Underlying risk

# Showcase

2024-06-27 10:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=4770) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=4770) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=4770) it.</sub>

2024-07-03 12:45 UTC, chenos requested changes

2024-07-03 12:45 UTC, chenos commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +              { type: 'integer', name: 'rootPK' },
nodePk 和 rootPk 不一定是 Integer 吧？

2024-07-03 12:45 UTC, chenos commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (!condition(options)) {
这个调整放这里没啥用

2024-07-03 12:45 UTC, chenos commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          await this.db.getCollection(name).sync();
这里为什么还会有 Sync 呢

2024-07-03 12:45 UTC, chenos commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +    this.db.on('afterSync', async (options) => {
这里的也需要 transaction

2024-07-03 14:20 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +              { type: 'integer', name: 'rootPK' },
![4fa3e936fd6bc5dcdf4e2b85efa7099e](https://github.com/nocobase/nocobase/assets/17548183/9b7adae0-8d03-4aa4-9e94-7e72ad80fc40)
目前树表里是定义为整数

2024-07-03 14:21 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (!condition(options)) {
已调整

2024-07-03 14:21 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          await this.db.getCollection(name).sync();
已重新调整

2024-07-03 14:22 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +    this.db.on('afterSync', async (options) => {
已重新调整

2024-07-04 01:54 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +              { type: 'integer', name: 'rootPK' },
这里的后面可能会调整成任意类型的，path 表需要获取源表字段的类型来创建对应的字段。

2024-07-04 02:06 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (dataSource instanceof SequelizeDataSource) {
这里之前给的示例有点问题，需要调整成
```ts
      const collectionManager = dataSource.collectionManager;
      if (collectionManager instanceof SequelizeCollectionManager) {
         // ...
      }
```

2024-07-04 02:38 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (dataSource instanceof SequelizeDataSource) {
我调整下

2024-07-27 14:30 UTC, 2013xile commented on packages/core/actions/src/actions/list.ts
> +      params.tree = true;
这个 if 条件可以去掉了

2024-07-27 14:33 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +      return [datas, datas.length];
return `await super.findAndCount(options)` ?

2024-07-27 14:50 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      await this.syncExistTreeCollectionPathTable();
看起来放在这里不对

2024-07-27 14:52 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +
```ts
this.db.on(`${name}.afterSync`, ({ transaction }) => {
  // 在这里初始化 collection 的 path 数据
  // 如果表里有数据，就不需要
});
```

2024-07-27 14:54 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +            let path = `/${model.dataValues?.id}`;
获取属性可以 `model.get('id')` 或 `model.id` 试试，另外这里最好不要直接用 `id`, 而是 collection 的 `filterTargetKey`

2024-07-27 14:56 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +            this.app.db.getRepository(name).destroy({
await

2024-07-27 14:58 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          if (!collection.options.tree) {
要么统一用 `condition` 判断，要么不要用 `condition` 都用 `collection.options.tree` 判断。下面有的代码判断跟这里不统一。

2024-07-27 15:07 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (parent) {
这里能否根据父节点 path 拼接新的 path，需要每次都递归构建 path 吗

2024-07-27 15:07 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          this.db.on(`${collection.name}.afterUpdate`, async (model, options) => {
更新是不是父节点有改变的时候才需要更新path？

2024-07-27 15:08 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/index.ts
> +    plugins: ['error-handler', 'data-source-main', 'ui-schema-storage', 'collection-tree'],
data-source-main 插件不依赖 collection-tree 才能使用，collection-tree 放进来不太好。

2024-07-27 15:10 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +      const nodeDatas = await this.queryRootDatas(nodeIds);
data已经是复数，不用加s

2024-07-27 15:12 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +      interface rootPathDataMapInterface {
interface 定义放到外面

2024-07-27 15:29 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    const pathTableName = `main_${collection.name}_path`;
`main` 要换乘数据源的 `key`

2024-07-27 15:49 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +  private async findCommonParent(strings: string[]): Promise<string | undefined> {
这个看起来不是 Promise 函数？

2024-07-27 15:51 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    }
找不到 path 表的时候可以打一个异常日志。

2024-07-28 03:29 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          this.db.on(`${collection.name}.afterDestroy`, async (model: Model, options: DestroyOptions) => {
子节点的path是不是需要一并删除。

原来删除了父节点、子节点也会被删除，这个 pr 上似乎有问题，父节点删除了，子节点没有删除。

2024-07-29 02:53 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +      return [datas, datas.length];
已修改为这个方法

2024-07-29 03:01 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          const name = `${dataSource.name}_${collection.options.name}_path`;
已采用

2024-07-29 03:04 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-data-source-main/src/server/__tests__/index.ts
> +    plugins: ['error-handler', 'data-source-main', 'ui-schema-storage', 'collection-tree'],
迁移collection-tree  test后忘记删除了，已清理

2024-07-29 03:10 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +            this.app.db.getRepository(name).destroy({
已修正

2024-07-30 02:39 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +
已优化

2024-07-30 02:49 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +      const nodeDatas = await this.queryRootDatas(nodeIds);
已优化

2024-07-30 02:59 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +      interface rootPathDataMapInterface {
已优化

2024-07-30 03:20 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    const pathTableName = `main_${collection.name}_path`;
已优化

2024-07-30 03:25 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +  private async findCommonParent(strings: string[]): Promise<string | undefined> {
已优化

2024-07-30 03:42 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    }
新增日志打印功能

2024-07-30 03:45 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +
已优化

2024-07-30 05:44 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +            let path = `/${model.dataValues?.id}`;
已优化实现

2024-07-30 05:45 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      await this.syncExistTreeCollectionPathTable();
暂时没想到更好的实现，待讨论

2024-07-30 05:46 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          this.db.on(`${collection.name}.afterDestroy`, async (model: Model, options: DestroyOptions) => {
已确认是bug

2024-07-31 03:03 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          this.db.on(`${collection.name}.afterDestroy`, async (model: Model, options: DestroyOptions) => {
已修正

2024-07-31 07:20 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      await this.syncExistTreeCollectionPathTable();
我测试过，这里程序启动后没有将已有的collection tree path表创建出来

2024-07-31 07:21 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          if (!collection.options.tree) {
这里我仔细看了下，上面的condition和下面的collection.options.tree判断实现功能一样，但是实现的功能应该不一样

2024-07-31 07:23 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (parent) {
在并发时，有可能会导致生成的path信息不准，是否按照父节点的path进行优化？

2024-07-31 07:24 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          this.db.on(`${collection.name}.afterUpdate`, async (model, options) => {
我打印了传递的参数，dataValues和_previousDataValues数据是一致的，是否有其他方式判断进行更新？

2024-07-31 11:04 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          if (!collection.options.tree) {
指的是28行和102行的。统一都用 `condition(collection.options)` 也可以。

2024-07-31 11:08 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (parent) {
即使是递归构建，也解决不了并发问题吧？parent仍然可能是旧数据。

2024-07-31 11:20 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          this.db.on(`${collection.name}.afterUpdate`, async (model, options) => {
model._changed 有变化吗，回头我测试一下。

2024-08-02 00:15 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          if (!collection.options.tree) {
已优化

2024-08-02 00:17 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (parent) {
数据更新时会触发更新path信号，每次取到的数据都是准确的，只不过递归的确是会有相应的性能损耗

2024-08-02 02:34 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +          this.db.on(`${collection.name}.afterUpdate`, async (model, options) => {
我测试了，可以用这个进行判断，已优化逻辑

2024-08-02 03:32 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (parent) {
比方说上面已经获取到了 `parent`, 此时假如 parent 节点的父节点改变了，下面拿到的 `parent.parentId` 也是旧的。此时触发的更新也是父节点 path 的更新，而不是这条记录 path 的更新。

另外基于 model 获取属性，都可以直接用 `model.get(key)` 或 `model[key]` 代替 `model.dataValues[key]`.

2024-08-02 03:36 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      const collectionTree = await this.db.getCollection(name);
`getCollection` 方法不需要 `await`

2024-08-02 04:08 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      const collectionTree = await this.db.getCollection(name);
已优化调整

2024-08-02 05:23 UTC, jimmy201602 commented on packages/core/actions/src/actions/list.ts
> +      params.tree = true;
已优化

2024-08-02 05:39 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +              { type: 'integer', name: 'rootPK' },
待以后一块优化

2024-08-02 06:48 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      await this.syncExistTreeCollectionPathTable();
已经迁移至migration功能

2024-08-02 07:27 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (parent) {
> 比方说上面已经获取到了 `parent`, 此时假如 parent 节点的父节点改变了，下面拿到的 `parent.parentId` 也是旧的。此时触发的更新也是父节点 path 的更新，而不是这条记录 path 的更新。
> 
> 另外基于 model 获取属性，都可以直接用 `model.get(key)` 或 `model[key]` 代替 `model.dataValues[key]`.

已更改

2024-08-02 08:15 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (parent) {
> 比方说上面已经获取到了 `parent`, 此时假如 parent 节点的父节点改变了，下面拿到的 `parent.parentId` 也是旧的。此时触发的更新也是父节点 path 的更新，而不是这条记录 path 的更新。
> 
> 另外基于 model 获取属性，都可以直接用 `model.get(key)` 或 `model[key]` 代替 `model.dataValues[key]`.

已优化

2024-08-05 09:26 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    this.collection.context.database.logger.warn(`Collection tree path table: ${pathTableName} not found`);
`this.database.logger`

2024-08-05 09:27 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-acl/src/server/__tests__/prepare.ts
> +      'collection-tree',
这个依赖可以去掉吗？

2024-08-05 09:31 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/package.json
> +  "name": "@nocobase/plugin-collection-tree",
加上
- `displayName` - Collection: Tree
- `displayName.zh-CN`-  数据表：树
- `description` - Provides tree collection template
- `description.zh-CN` - 提供树数据表模板
还有
```json
  "keywords": [
    "Collections"
  ]
```

2024-08-05 09:53 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    this.collection.context.database.logger.warn(`Collection tree path table: ${pathTableName} not found`);
已优化

2024-08-05 09:53 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +            const collectionTreePath = await this.app.db.getCollection(name);
不需要 await 的，另外可以直接用 this.db

2024-08-05 10:06 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-acl/src/server/__tests__/prepare.ts
> +      'collection-tree',
auth collection-tree可以移除,data-source-main、data-source-manager无法移除，有依赖

2024-08-05 10:11 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/package.json
> +  "name": "@nocobase/plugin-collection-tree",
已添加信息

2024-08-05 10:17 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +            const collectionTreePath = await this.app.db.getCollection(name);
已优化

2024-08-05 12:37 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-acl/src/server/__tests__/prepare.ts
> +      'collection-tree',
移除 `collection-tree` 即可。

2024-08-06 03:35 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts
> +      this.app.db.collection({
这个表定义内容可以抽出来，我看似乎好几个地方都用到了。

2024-08-06 03:35 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts
> +        this.app.db.collection({
这里的表定义似乎不是必须的？

2024-08-06 03:37 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts
> +        const existData = await this.app.db.getRepository(treeCollection.name).find({});
可以用 `repository.chunk` 方法分批处理。
另外写入的时候可以都先放到数组里再一次性执行数据库写入。
```ts
await this.db.getModel(name).bulkCreate()
```

2024-08-06 07:05 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts
> +        const existData = await this.app.db.getRepository(treeCollection.name).find({});
已优化

2024-08-06 07:14 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts
> +        this.app.db.collection({
这里必须定义，我测试过很多次，此时没有collection表定义的

2024-08-06 07:16 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/migrations/20240802141435-collection-tree.ts
> +      this.app.db.collection({
考虑到多数据源的问题，应该是用数据源名称比较合理，如果这里有获取数据源名的方式方法，就能做到全部统一了

2024-08-06 14:37 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (parent && parent.get('parentId') !== model.get(collection.filterTargetKey)) {
这里的 `path` 是不是等于 `${parent.path}/${model.get(collection.filterTargetKey}` 就可以?

另外这里的查询的话，看起来也应该带上 `transaction`.

2024-08-07 08:00 UTC, jimmy201602 commented on packages/plugins/@nocobase/plugin-collection-tree/src/server/plugin.ts
> +      if (parent && parent.get('parentId') !== model.get(collection.filterTargetKey)) {
已加transaction

2024-08-08 05:31 UTC, chenos commented on packages/core/actions/src/actions/list.ts
> +    if (!isValidFilter(params.filter)) {
这里为啥要这样处理呢

2024-08-08 05:33 UTC, chenos commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    options = lodash.omit(options, 'filter.childIds');
childIds 为啥是在这里？

2024-08-08 05:34 UTC, chenos commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    options = lodash.omit(options, 'filter.childIds');
childIds 放在 filter 里不太合适，如果需要也是单独一个参数

2024-08-08 06:03 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    options = lodash.omit(options, 'filter.childIds');
方便进行树节点重组，因为以前的代码没有满足需求，做了个小改造，以前的代码不敢改太多

2024-08-08 06:03 UTC, jimmy201602 commented on packages/core/actions/src/actions/list.ts
> +    if (!isValidFilter(params.filter)) {
以前的代码tree功能移除了，做的最小适配改造

2024-08-08 14:08 UTC, jimmy201602 commented on packages/core/actions/src/actions/list.ts
> +    if (!isValidFilter(params.filter)) {
已优化

2024-08-10 16:29 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    const filterNodes = await super.find({ ...lodash.omit(options, ['limit', 'offset']) });
只捞 id 比较好？`fields: [primaryKey]`

2024-08-10 16:30 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    const nodeData = await this.queryRootDatas(filterIds, options.context?.dataSource?.name ?? 'main');
Data 已经是复数。

2024-08-10 16:35 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    const filterNodes = await super.find({ ...lodash.omit(options, ['limit', 'offset']) });
另外感觉前面可以再加个判断
```ts
if (!isValidFilter(options.filter)) {
  return await super.find({ ...options, filter: { parentId: null }});
}
```
空筛选条件的时候就不用走到这里了，尽可能避免把全量数据拉出来占用比较大的内存空间。

2024-08-11 02:05 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    const nodeData = await this.queryRootDatas(filterIds, options.context?.dataSource?.name ?? 'main');
已优化

2024-08-11 02:08 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    const filterNodes = await super.find({ ...lodash.omit(options, ['limit', 'offset']) });
> ```ts
> ```ts
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

这样的话，查询的数据结果貌似不一定符合预期，查询数据为空时，需要组装一棵完整的树结构数据

2024-08-11 02:08 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    const filterNodes = await super.find({ ...lodash.omit(options, ['limit', 'offset']) });
> 第一步这里只捞 id 比较好？`fields: [primaryKey]`

已优化

2024-08-11 02:08 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +    options = lodash.omit(options, 'filter.childIds');
已重新实现

2024-08-11 05:55 UTC, 2013xile commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +      ...lodash.omit(options, ['limit', 'offset', 'filterByTk', 'filter']),
这里是不是不能省略 `limit`, `offset`, 现在好像分页查询有问题，每次都返回了全部数据。

2024-08-11 06:46 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +      ...lodash.omit(options, ['limit', 'offset', 'filterByTk', 'filter']),
我测试下

2024-08-11 06:54 UTC, jimmy201602 commented on packages/core/database/src/repositories/tree-repository/adjacency-list-repository.ts
> +      ...lodash.omit(options, ['limit', 'offset', 'filterByTk', 'filter']),
我改了下，再跑下全量测试

2024-08-13 01:42 UTC, merged