feat: support notification
nocobase/nocobase pull request #4926
Opened 2024-07-22 06:12 UTC by sheldon66

### This is a ...
- [x] New feature
- [ ] Improvement
- [ ] Bug fix
- [ ] Others

### Motivation

To support sending various notifications.
### Description 

Add a notification plugin that su

### Related issues

### Showcase

### Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |     add notification feature      |
| 🇨🇳 Chinese |       增加通知功能    |

### Docs

| Language   | Link |
| ---------- | --------- |
| 🇺🇸 English |      |
| 🇨🇳 Chinese |    |

### Checklists
- [ ] All changes have been self-tested and work as expected
- [ ] Test cases are updated/provided or not needed
- [ ] Doc is updated/provided or not needed
- [ ] Component demo is updated/provided or not needed
- [ ] Changelog is provided or not needed
- [ ] Request a code review if it is necessary

2024-07-22 06:21 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notifications/src/server/plugin.ts
> +  }
这部分弄个单独的类吧

```
export class PluginNotificationManagerServer extends Plugin {
  notificationsManager: NotificationsManager;
}
```

2024-07-24 01:43 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/message/components/ReceiverConfigForm.tsx
> +    const AddItem = () => {
这里可以用 formily 的组件 ArrayItems
配合 SchemaComponent https://client.docs.nocobase.com/core/ui-schema/schema-component

2024-07-29 02:14 UTC, sheldon66 commented on packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/message/components/ReceiverConfigForm.tsx
> +    const AddItem = () => {
好的，已经更正

2024-08-05 02:54 UTC, 2013xile commented on packages/core/client/src/data-source/collection-field/CollectionFieldProvider.tsx
> +    //在这里调试
记得去掉

2024-08-05 02:57 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notifications/src/server/plugin.ts
> +  }
@sheldon66 这里还没改

2024-08-05 03:04 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-mail/src/client/ConfigForm.tsx
> +            title: '{{t("host")}}',
文案类的都先修改一下：
- 标题首字母大写
- 多个单词的情况下，只有第一个单词的首字母大写
- 表单统一用上下排版，一些特殊的地方，比如一些 checkbox, 需要横向排版的，schema里用 'x-content' 代替 'title'
- i18n 文件需要有 `en-US`, 不要只有 `zh-CN`

2024-08-05 03:28 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/client/index.tsx
> +export class PluginNotificationCoreClient extends Plugin {
PluginNotificationManagerClient

2024-08-05 03:29 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/client/index.tsx
> +    console.log(this.app);
最后 merge 前要检查一遍，把 `console` 的东西去掉，暂时不去也可以。

2024-08-05 03:38 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +  async send(message: IMessage) {
感觉 `message`, `IMessage` 命名不好，这里面包含了 `receivers`, `channelId` 等信息，初看容易误解，尤其是这里也没有解构，就直接把 `message` 透传了。
可能 `options: SendOptions` 更合适。

2024-08-05 03:39 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    logsRepo.create({ values: { channelId: message.channelId, triggerFrom: message.triggerFrom, status: 'success' } });
这里状态不一定是 `success` 吧？

2024-08-05 04:11 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/store.ts
> +export class NotificationPluginStorer {
这个用在哪里了？

2024-08-05 04:18 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +      const messagesRepo = ctx.db.getRepository('messages');
这个接口还是保留，但是不从 messages 表里拿消息了，支持从前端直接传参，后面可以给自定义请求之类的用。

另外接口需要通过 `registerSnippets` 设置权限。

2024-08-06 03:16 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/client/manager/template/schemas/table.ts
> +      title: '{{t("Notification Type")}}',
Notification type

2024-08-06 03:16 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-mail/src/server/plugin.ts
> +    notificationServer.registerTypes(channelType, {
展示的时候首字母要大写，可以加一个 title 参数 作为展示标题。

2024-08-07 01:09 UTC, sheldon66 commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    logsRepo.create({ values: { channelId: message.channelId, triggerFrom: message.triggerFrom, status: 'success' } });
> 另外 log 需要将 receivers 也记录下来? 可能每个 receiver 需要一条记录？感觉这里 send 的响应可以考虑支持两种情况：
> 1. 渠道接口只能统一响应成功或失败，只记录一条 log
> 2. 渠道接口可以响应每个 receiver 的状态，分别记录 log
当时想的是记录一下这条消息发给哪些人了，我觉得不需要每个receiver一条记录了把，如果渠道接口可以相应每一个receiver的状态，返回一个数据{receiverA: "success", receiverB: "failed"}这样可以么

2024-08-07 01:10 UTC, sheldon66 commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/store.ts
> +export class NotificationPluginStorer {
这个最后没有用，我删一下

2024-08-07 01:28 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    logsRepo.create({ values: { channelId: message.channelId, triggerFrom: message.triggerFrom, status: 'success' } });
数据量大的时候可能比较难记录。

2024-08-07 02:40 UTC, sheldon66 commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    logsRepo.create({ values: { channelId: message.channelId, triggerFrom: message.triggerFrom, status: 'success' } });
那不然就统一每个receiver一条记录，即使渠道接口只能统一相应成功或失败，也这样记，便于后面统计

2024-08-07 04:38 UTC, sheldon66 commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    logsRepo.create({ values: { channelId: message.channelId, triggerFrom: message.triggerFrom, status: 'success' } });
唯一的不好可能是每个receiver一条记录，最后表的数据量可能会比较大？

2024-08-07 05:01 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    logsRepo.create({ values: { channelId: message.channelId, triggerFrom: message.triggerFrom, status: 'success' } });
流水表这种记录都会比较大，即使是统一记，时间长了也是一样的。这种可以后面讨论怎么一下处理，是分表、还是定期清理，设置最大保留时间等等。

2024-08-07 05:17 UTC, sheldon66 commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    logsRepo.create({ values: { channelId: message.channelId, triggerFrom: message.triggerFrom, status: 'success' } });
好的，那我就按每个receiver一条记录这个方案调整一下

2024-08-07 07:43 UTC, mytharcher requested changes

2024-08-07 07:43 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-workflow-notification/src/server/NotificationInstruction.ts
> +    return processor.exit();
这里直接退出的话，是不会重新进入后面的 resume 回调的。可以参考 request 或者 mail 节点的处理逻辑，主要是区分同步异步处理。

2024-08-09 12:31 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/collections/messageLog.ts
> +      type: 'nanoid',
用 uuid 比较好

2024-08-09 12:32 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/collections/channel.ts
> +      type: 'nanoid',
这里uid，string类型，在前端随机生成的，也可以给用户自定义。参考用户认证器标识、数据表标识等

2024-08-09 12:35 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    this.app.acl.allow('messages', 'send', 'loggedIn');
这个接口不是登录了就允许调用的。

2024-08-09 12:35 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +  async send(options: SendOptions) {
这个也是 Manager 里的 API

2024-08-09 12:36 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +export class PluginNotificationManager extends Plugin {
PluginNotificationManagerServer

2024-08-09 12:37 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +  createSendingRecord = async (options: WriteLogOptions) => {
这个也应该放到 Manager 里

2024-08-09 12:38 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    notificationServer.send({ message: options, channel, createSendingRecord: this.createSendingRecord });
不应该把 create 方法传过去，应该获取到结果，在内部处理记录创建。

2024-08-11 12:23 UTC, sheldon66 commented on packages/plugins/@nocobase/plugin-notification-manager/src/server/plugin.ts
> +    this.app.acl.allow('messages', 'send', 'loggedIn');
是有通知插件的权限？

2024-08-12 02:14 UTC, mytharcher approved these changes
LGTM

2024-08-14 02:13 UTC, chenos commented on packages/plugins/@nocobase/plugin-notification-manager/src/collections/channel.ts
> +      name: 'id',
这种不是 Integer 的最好就不要叫 id 了，叫 name 或者 key 比较合适

2024-08-14 02:16 UTC, chenos commented on packages/plugins/@nocobase/plugin-notification-manager/src/constant.ts
> +}
以前的有历史包袱，新建的表，尽量都加上前缀，比如：
- notificationTemplates
- notificationChannels
- notificationMessages
- notificationLogs

如果 notificationTemplates 和 notificationMessages 不要了，可以考虑删掉

2024-08-14 02:23 UTC, chenos requested changes
表名、字段名不合适的要在发布前改掉，不留历史包袱
不用的表也可以删掉，相关代码也删掉，方便 code review

2024-09-06 00:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=4926) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=4926) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=4926) it.</sub>

2024-09-26 10:46 UTC, chenos commented on packages/plugins/@nocobase/plugin-notification-mail-smtp/src/client/index.tsx
> +      name: channelType,
这里叫 name 不合适，注册的是 type，每个 type 可以有多个 name 的 channel

2024-09-28 15:55 UTC, merged