feat: pub/sub manager
nocobase/nocobase pull request #4933
Opened 2024-07-23 02:42 UTC by chenos

### This is a ...
- [ ] New feature
- [ ] Improvement
- [ ] Bug fix
- [ ] Others

### Motivation

### Description 

### Related issues

### Showcase

### Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### Docs

| Language   | Link |
| ---------- | --------- |
| 🇺🇸 English |      |
| 🇨🇳 Chinese |    |

### Checklists
- [ ] All changes have been self-tested and work as expected
- [ ] Test cases are updated/provided or not needed
- [ ] Doc is updated/provided or not needed
- [ ] Component demo is updated/provided or not needed
- [ ] Changelog is provided or not needed
- [ ] Request a code review if it is necessary

2024-07-23 02:44 UTC, chenos commented on packages/core/server/src/application.ts
> +      await this.pubSubManager.close();
应用有个 reload 的机制，这些模块都需要 close

2024-07-23 02:45 UTC, chenos commented on packages/core/server/src/__tests__/pub-sub-manager.test.ts
> +      name: 'node1',
应用是不同的，但是 pubSub 是相同的，各自管各自的

2024-07-23 02:46 UTC, chenos commented on packages/core/server/src/__tests__/pub-sub-manager.test.ts
> +export class RedisPubSubAdapter implements IPubSubAdapter {
这个只是简单实现了一下，忽略掉内部细节

2024-07-23 02:46 UTC, chenos commented on packages/core/server/src/pub-sub-manager.ts
> +}
PubSubAdapter 的基本流程，与 App 无关

2024-07-25 09:30 UTC, chareice commented on packages/core/server/src/pub-sub-manager.ts
> +  get basename() {
basename 这种命名感觉不够清晰，可以叫 channelPrefix

2024-07-25 09:33 UTC, chareice commented on packages/core/server/src/pub-sub-manager.ts
> +    this.connected = true;
状态变更需要在 adapter.connect 执行完成之后执行，否则connect 出错时状态标记不正确

2024-07-25 09:42 UTC, chareice commented on packages/core/server/src/pub-sub-manager.ts
> +    return crypto.createHash('sha256').update(JSON.stringify(message)).digest('hex');
这里同步计算 hash 值有卡事件循环的风险，可以换成 crypto.subtle.digest  https://nodejs.org/api/webcrypto.html#subtledigestalgorithm-data

2024-07-25 10:12 UTC, chareice commented on packages/core/server/src/pub-sub-manager.ts
> +  async subscribeAll(callback, options: PubSubManagerSubscribeOptions = {}) {
大部分内容和 subscribe 重复，需封装

2024-07-25 10:16 UTC, chareice commented on packages/core/server/src/pub-sub-manager.ts
> +  async unsubscribe(channel, callback) {
subscribe 时向 this.subscribes 写了内容，但是 unsubscribe 中未清理

2024-07-25 13:13 UTC, 2013xile commented on packages/core/server/src/pub-sub-manager.ts
> +  messageHanders = new Map();
messageHandlers

2024-07-25 13:20 UTC, 2013xile commented on packages/core/server/src/pub-sub-manager.ts
> +  static create(app: Application, options: PubSubManagerOptions) {
感觉 pubsub 可以单独一个 package.
然后这个方法抽出去，类似 https://github.com/nocobase/nocobase/blob/main/packages/core/server/src/cache/index.ts

2024-07-25 15:32 UTC, mytharcher requested changes

2024-07-25 15:32 UTC, mytharcher commented on packages/core/server/src/pub-sub-manager.ts
> +    if (!this.messageHandlers.has(messageHash)) {
用 `messageHandlers` 来保存基于 hash 的 debounce handler 这个策略是有问题的。消息内容并不都是固定的，比如消息如果传了基于数据 id 或者时间戳之类的数据，这里的 handlers 就会无限增长了。

2024-07-26 01:07 UTC, chenos commented on packages/core/server/src/pub-sub-manager.ts
> +    if (!this.messageHandlers.has(messageHash)) {
后面少了个 delete，callback 执行完就会销毁掉，不会无限增长

2024-07-31 02:29 UTC, mytharcher requested changes

2024-07-31 02:29 UTC, mytharcher commented on packages/core/server/src/application.ts
> +      channelPrefix: this.name,
`channelPrefix` 对通用场景默认定义为 app.name 有些鸡肋，如果 NocoBase 应用和其他类型的微服务共用信道，则限制了信道名称格式，且主子应用也无法通信。

鉴于 SyncMessageManager 中已经通过 app.name 定义了业务信道前缀，这里的默认值应该移除。

2024-08-14 04:09 UTC, merged