Feat/encryption field
nocobase/nocobase pull request #4975
Opened 2024-08-01 02:25 UTC by dream2023

### This is a ...
- [ ] New feature
- [ ] Improvement
- [ ] Bug fix
- [ ] Others

### Motivation

### Description 

### Related issues

### Showcase

### Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### Docs

| Language   | Link |
| ---------- | --------- |
| 🇺🇸 English |      |
| 🇨🇳 Chinese |    |

### Checklists
- [ ] All changes have been self-tested and work as expected
- [ ] Test cases are updated/provided or not needed
- [ ] Doc is updated/provided or not needed
- [ ] Component demo is updated/provided or not needed
- [ ] Changelog is provided or not needed
- [ ] Request a code review if it is necessary

2024-08-01 10:10 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-field-encryption/src/server/plugin.ts
> +    this.db.on('fields.beforeCreate', (model, field) => {
`model.type`

2024-08-01 10:10 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-field-encryption/src/server/plugin.ts
> +      if (field.values?.type === 'encryption') {
`model.type`

2024-08-01 10:10 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-field-encryption/src/server/encryption-field.ts
> +    this.on('beforeUpdate', this.writeListener);
`beforeSave` = `beforeCreate` + `beforeUpdate`

2024-08-01 22:56 UTC, 2013xile requested changes
测试用例是不是还要补一些？搜索、解密、创建字段报错这些。

2024-08-02 01:36 UTC, dream2023 commented
> 测试用例是不是还要补一些？搜索、解密、创建字段报错这些。

肯定要写，还没文档、单测、e2e 今天写

2024-08-09 09:14 UTC, merged