feat(server): add lock manager to server
nocobase/nocobase pull request #5042
Opened 2024-08-12 06:09 UTC by mytharcher

### This is a ...

- [x] New feature
- [ ] Improvement
- [ ] Bug fix
- [ ] Others

### Motivation

To provide an adapt layer for lock usages.

### Description 

Any further usage of lock could start from `app.lockManager`.

### Related issues

None.

### Showcase

None.

### Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### Docs

| Language   | Link |
| ---------- | --------- |
| 🇺🇸 English |      |
| 🇨🇳 Chinese |    |

### Checklists

- [ ] All changes have been self-tested and work as expected
- [ ] Test cases are updated/provided or not needed
- [ ] Doc is updated/provided or not needed
- [ ] Component demo is updated/provided or not needed
- [ ] Changelog is provided or not needed
- [ ] Request a code review if it is necessary

2024-08-13 03:07 UTC, chenos requested changes

2024-08-13 03:07 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +  async getLock(key: string, ttl = 500): Promise<AbstractLock> {
现在的这块设计缺少了几个东西
1. client 的管理，尤其是 client close 的问题
2. 这里是 createLock，叫 getLock 不太合适，这里的步骤包括
  1. 获取 client，如果没有则 new 一个并连接上，放内存待用
  2. 如果有 client 则 new Lock，这时候 client 的 lock 还没创建，只是创建的 adapter 实例，lock.acquire 时才会创建 lock 实例

2024-08-13 03:07 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +  async getLock(key: string, ttl = 500): Promise<AbstractLock> {
![image](https://github.com/user-attachments/assets/ab0298f5-b6ae-405d-b450-640f7cc53be4)

2024-08-13 03:07 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +    return lock;
这里的实现看起来也不太对

2024-08-13 03:07 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +      await lock.release();
release 的是 acquire 的 lock，看起来不太对

2024-08-14 04:47 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +      Client: LocalLockAdapter,
现在只有 Adapter，那这里注册就都叫 Adapter 比较好吧，不叫 Client 了

2024-08-14 04:48 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +  [key: string]: any;
这里弄成两个参数比较合适
{
  Adapter,
  options,
}

2024-08-14 04:50 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +}
这里弄成 interface 比较合适，叫 `ILockAdapter`，connect 和 close 是都需要实现的，并不是默认可以不实现

2024-08-14 04:50 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +  private clients = new Map<string, AbstractLockAdapter>();
这里叫 adapters 比较合适

2024-08-14 04:51 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +  private async getClient(): Promise<AbstractLockAdapter> {
getAdapter

2024-08-14 04:55 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +      await client.connect();
现在还缺个 close 的方法，要把 connect 的 adapter 关掉，在应用重载、重启、停止时会用到

![image](https://github.com/user-attachments/assets/efad35f9-c11b-424d-a175-204d6536fbd3)

2024-08-14 05:13 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +  private getLock(key: string, ttl: number): LocalLock {
LocalLock 的实现，用类静态属性的单例模式的思路来弄比较合适，现在这个实现，无法多应用里使用。

```ts
class LocalLock {
  static instances = new Map<string, LocalLock>();

  static create(key: string, options?: any) {
    if (!this.instances.has(key)) {
      this.instances.set(key, new LocalLock(options));
    }
    return this.instances.get(key);
  }

  constructor(protected options) {}
}
```

2024-08-14 15:48 UTC, mytharcher commented on packages/core/server/src/lock-manager.ts
> +}
本地锁是可以不实现的。

2024-08-15 07:35 UTC, chenos commented on packages/core/server/src/lock-manager.ts
> +}
在 ILockAdapter 层面是需要实现的，只是本地锁可以简化，这里的设计并不是继承关系，而是需要适配器需要实现这些接口

2024-08-20 02:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=5042) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=5042) before we can accept your contribution.<br/>**8** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: katherinehhh<br/>:white_check_mark: zhangzhonghe<br/>:white_check_mark: sheldon66<br/>:white_check_mark: chenos<br/>:white_check_mark: 2013xile<br/>:white_check_mark: jiarakucloud<br/>:white_check_mark: mytharcher<br/>:white_check_mark: chareice<br/>:x: actions-user<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=5042) it.</sub>

2024-11-20 15:57 UTC, closed without merging