Feat/plugin-notification-in-app
nocobase/nocobase pull request #5254
Opened 2024-09-11 08:09 UTC by sheldon66

### This is a ...
- [x] New feature
- [ ] Improvement
- [ ] Bug fix
- [ ] Others

### Motivation

### Description 

### Related issues

### Showcase

### Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### Docs

| Language   | Link |
| ---------- | --------- |
| 🇺🇸 English |      |
| 🇨🇳 Chinese |    |

### Checklists
- [ ] All changes have been self-tested and work as expected
- [ ] Test cases are updated/provided or not needed
- [ ] Doc is updated/provided or not needed
- [ ] Component demo is updated/provided or not needed
- [ ] Changelog is provided or not needed
- [ ] Request a code review if it is necessary

2024-09-11 08:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=5254) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=5254) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=5254) it.</sub>

2024-10-11 02:06 UTC, chareice commented on packages/plugins/@nocobase/plugin-notification-in-app/src/server/InAppNotificationChannel.ts
> +              logging: console.log,
去掉logging，database 会统一处理

2024-10-24 15:38 UTC, mytharcher requested changes

2024-10-24 15:38 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-notification-in-app-message/src/client/observables/sse.tsx
> +    const res = await apiClient.silent().request({
这里调用 `.silent()` 会导致 `silence` 属性本保存在 apiClient 中，之后所有请求也都变为静默模式，错误通知无法在页面弹出。

参考 APIClient 的代码：

```
  silent() {
    this.silence = true;
    return this;
  }
```

需要改个方式实现。

2024-10-25 14:41 UTC, merged