Feat/token-security
nocobase/nocobase pull request #5948
Opened 2024-12-26 00:06 UTC by sheldon66

### This is a ...
- [x] New feature
- [ ] Improvement
- [ ] Bug fix
- [ ] Others

### Motivation

feat: token security
### Description 

### Related issues

### Showcase

### Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |           |
| 🇨🇳 Chinese |           |

### Docs

| Language   | Link |
| ---------- | --------- |
| 🇺🇸 English |      |
| 🇨🇳 Chinese |    |

### Checklists
- [ ] All changes have been self-tested and work as expected
- [ ] Test cases are updated/provided or not needed
- [ ] Doc is updated/provided or not needed
- [ ] Component demo is updated/provided or not needed
- [ ] Changelog is provided or not needed
- [ ] Request a code review if it is necessary

2024-12-26 07:46 UTC, 2013xile commented on packages/core/auth/package.json
> +    "async-mutex": "^0.5.0"
不需要这个，用 `lock-manager`，兼容分布式

2024-12-26 07:58 UTC, 2013xile commented on packages/core/auth/src/auth-manager.ts
> +          if (!isPublicAction || ['auth:check'].includes(`${resourceName}:${actionName}`)) {
`auth:check` 好像本来就是 public 的？

2024-12-26 07:58 UTC, 2013xile commented on packages/core/auth/src/auth-manager.ts
> +      if (rawResourceName.includes('.')) {
这里好像不应该截断 `resourceName` ?

2024-12-26 08:01 UTC, 2013xile commented on packages/core/auth/src/auth-manager.ts
>      return async function AuthManagerMiddleware(ctx: Context & { auth: Auth }, next: Next) {
按之前讨论的，理想情况这部分改动应该拆分一个中间件

2024-12-26 08:03 UTC, 2013xile commented on packages/core/auth/src/base/auth.ts
> +      throw new Error('Empty token');
这里好像会导致有时候刚一进页面调用了 `auth:check` 右上角就弹出报错 `Empty token`

2024-12-26 08:03 UTC, 2013xile commented on packages/core/auth/src/base/auth.ts
> +        throw new Error('Password expired');
这个不是密码过期，是修改密码重新登录

2024-12-26 08:06 UTC, 2013xile commented on packages/core/auth/src/base/jwt-service.ts
> +    const opt = { ...options, expiresIn, jwtid: options?.jwtid || this.accessController.addAccess() };
这是不是把 jti, expireIn 从外面传进来就可以了，没必要把 accessController 也注入到 jwtService. 另外要保留原来的 `process.env.JWT_EXPIRE_IN`

2024-12-26 08:08 UTC, 2013xile commented on packages/core/client/src/locale/en-US.json
> +  "Access control": "Access control",
这里开始下面的要放到 `plugin-auth` 插件里

2024-12-26 08:09 UTC, 2013xile commented on packages/core/client/src/pm/index.tsx
> +    addSecuritySettingsPlugin(this.app);
这个方法感觉没必要，用标准 API 注册就可以了

2024-12-26 08:10 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-auth/src/server/access-controller.ts
> +import { Mutex } from 'async-mutex';
要用锁的话用 `lock-manager`

2024-12-26 08:15 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-auth/src/server/access-controller.ts
> +  private accessMap: Map<string, AccessInfo> = new Map();
这个是 jti 的缓存么，考虑分布式，用 cache，不要用内存缓存

2024-12-26 08:18 UTC, 2013xile requested changes
需要补充服务端测试

2024-12-27 04:04 UTC, sheldon66 commented on packages/core/auth/src/base/jwt-service.ts
> +    const opt = { ...options, expiresIn, jwtid: options?.jwtid || this.accessController.addAccess() };
this.exiresIn() 会读取 process.env.JWT_EXPIRE_IN，这个是原来的逻辑。
我把 jti, expireIn 改成从外面传进来。

2024-12-29 04:34 UTC, 2013xile commented on packages/core/acl/src/allow-manager.ts
> +  getAllowedConditions(
看了一下 `isAllowed` 是不是实际就是 `isPublic` ?

2024-12-29 04:38 UTC, 2013xile commented on packages/core/auth/src/auth-manager.ts
> +  checkMiddleware() {
这里要拆分的意思是看能否一个中间件检查 token 记录 token 状态，一个判断是不是公开接口，决定是响应报错还是往下走。现在这样拆好像差别不太大。

2024-12-29 04:43 UTC, 2013xile commented on packages/core/auth/src/auth.ts
> +  authenticate(): Promise<any>;
这个好像就是 check 干的事？

2024-12-29 07:07 UTC, sheldon66 commented on packages/core/acl/src/allow-manager.ts
> +  getAllowedConditions(
不是吧..., 我看isAllow是计算是否允许访问，不区分是否公开？

2024-12-29 07:09 UTC, sheldon66 commented on packages/core/auth/src/auth-manager.ts
> +  checkMiddleware() {
好，我按这个思路改一下

2024-12-30 03:30 UTC, chenos requested changes

2024-12-30 03:30 UTC, chenos commented on packages/core/auth/package.json
> +    "dependencies": {
多了缩略

2024-12-30 03:30 UTC, chenos commented on packages/core/client/src/acl/ACLProvider.tsx
> +    return <>{props.children}</>;
这个是为啥，看起来不对

2024-12-30 03:30 UTC, chenos commented on packages/core/client/src/api-client/APIClient.ts
> +    );
这一堆感觉不太适合在这里

2024-12-30 03:30 UTC, chenos commented on packages/core/server/src/application.ts
> +    this._dataSourceManager.use(this._authManager.checkMiddleware(), { tag: 'auth' });
这里不应该调整

2024-12-30 03:30 UTC, chenos commented on packages/core/test/playwright/tests/auth.setup.ts
> +  setup.setTimeout(120000);
去掉

2024-12-30 03:48 UTC, sheldon66 commented on packages/core/auth/src/auth-manager.ts
> -          message: ctx.t('Token is invalid'),
错误处理参考这里

2024-12-30 03:58 UTC, sheldon66 commented on packages/core/auth/src/auth-manager.ts
>     */
包一个compose

2024-12-31 08:22 UTC, sheldon66 commented on packages/plugins/@nocobase/plugin-auth/src/client/interceptors.ts
> +/**
@chenos @2013xile 把401重定向拦截器放到了插件里。就是还有一个执行顺序的问题，重定向的时候右上角会有 unauthorized 错误

2024-12-31 15:23 UTC, 2013xile commented on packages/core/test/src/server/mock-server.ts
> +  const app: MockServer = mockServer({ auth: false, ...others });
不应该在全局上加，不加这个是哪个用例会报错，可以提供一个具体的例子我看看。

2024-12-31 15:23 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-auth/src/client/index.tsx
> +      title: `{{t("Access control", { ns: "${NAMESPACE}" })}}`,
感觉 Access control 的说法容易产生歧义，例如
<img width="679" alt="image" src="https://github.com/user-attachments/assets/b446a12f-8e35-4338-9240-1f522c76b7c3" />
直白一点可以叫 Token policy, 如果不考虑 Session 的说法可能引起误会也可以叫 Sessions control

2024-12-31 15:23 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-auth/src/server/collections/access-control-config.ts
> +import { tokenControlConfigCollectionName } from '../../constants';
表名要改的话，是不是文件名也要改。
感觉配置表可以直接叫：`tokenPolicy`
token 的信息记录表可以叫 `issuedTokens` 
这样表名、变量名都不会太长

2024-12-31 15:23 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-auth/src/server/token-controller.ts
> +type AccessService = ITokenControlService<TokenInfo>;
命名要统一

2024-12-31 15:23 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-auth/src/server/token-controller.ts
> +        await Promise.all([this.cache.set(`access:${id}`, value), createOrUpdate(id, value)]);
数据库执行成功后再更新缓存，否则可能会数据不一致。

2024-12-31 15:23 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-error-handler/src/server/error-handler.ts
> +          data: err.data,
这个是做什么用的，标准化的东西都不要轻易改动。

2024-12-31 15:23 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-auth/src/server/token-controller.ts
> +export class TokenController implements AccessService {
数据库里的token信息历史记录是不是需要一个清理机制。

2024-12-31 15:23 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-auth/src/server/token-controller.ts
> +  private tokenMap: {
有点没理解这里为什么又包了一层 tokenMap 
似乎就是 getTokenInfo, setTokenInfo 两个私有函数，调用的时候 `this.getTokenInfo`, `this.setTokenInfo` 似乎更简单清晰。

2025-01-04 14:25 UTC, 2013xile requested changes

2025-01-04 14:25 UTC, 2013xile commented on packages/plugins/@nocobase/plugin-action-template-print
这个要去掉

2025-01-06 10:58 UTC, 2013xile requested changes

2025-01-06 10:58 UTC, 2013xile commented on packages/core/auth/package.json
> +    "koa-compose": "^4.1.0"
这个可以去掉了吧

2025-01-08 14:29 UTC, chenos requested changes
除了评论的问题以外，作为内核模块，测试用例也并不完整

2025-01-08 14:29 UTC, chenos commented on packages/core/auth/src/__tests__/middleware.test.ts
> -      expect(res.text).toContain('Token is invalid');
这个 text 的如果改了需要改成新的不是删掉

2025-01-08 14:29 UTC, chenos commented on packages/core/auth/src/__tests__/middleware.test.ts
> +      const res = await agent.resource('roles').check();
这里测的是 auth:check 不是 roles:check

2025-01-08 14:29 UTC, chenos commented on packages/core/auth/src/__tests__/base-auth.test.ts
> +    await expect(auth.signIn()).rejects.toThrow();
throw 的结果也要符合预期，不能省略

2025-01-08 14:29 UTC, chenos commented on packages/core/auth/src/auth.ts
> +  | 'NOT_EXIST_USER';
这里一堆 AuthErrorType 缺少测试用例覆盖

2025-01-08 14:29 UTC, chenos commented on packages/core/auth/src/base/auth.ts
> +        code: 'INVALID_TOKEN' satisfies AuthErrorType,
大量的 satisfies AuthErrorType 不是一个最佳的写法，应该是在全局维护一个枚举，然后这里

code: AuthErrorType.INVALID_TOKEN 这样直接使用

2025-01-18 14:18 UTC, merged