Chore/plugin field sequence update
nocobase/nocobase pull request #5959
Opened 2024-12-27 06:55 UTC by kennnnnnnnnn

add random number and random string patterns

- Add random number pattern with configurable length (padded with zeros)
- Add random string pattern with configurable length (alphanumeric)
- Update Chinese translations for new patterns
### This is a ...
- [x] New feature
- [ ] Improvement
- [ ] Bug fix
- [ ] Others

### Motivation

It is inconvenient to generate random values such as redemption coupons.
不方便生成兑换券之类的随机值。
### Description 

新增了两种序列号生成规则
定长随机数字：可配置位数，不足位数前面补0
随机字符串：可配置长度，包含大小写字母和数字
随机数字示例 (6位)
"123456" -> "000123"
随机字符串示例 (6位)
"Ax9bY2"
测试建议：
测试不同位数的随机数字生成
测试随机字符串的字符组成（是否包含大小写字母和数字）
测试位数限制（1-10位）是否生效
测试与其他规则的组合使用
额没怎么用过git有问题多担待。
### Related issues

### Showcase

<img width="862" alt="image" src="https://github.com/user-attachments/assets/1bf7ac0f-fd70-4497-b0cf-423fc353ddd5" />
<img width="179" alt="image" src="https://github.com/user-attachments/assets/d1d292b2-10c5-44d4-bcc4-8de0e9fe34d2" />

### Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English | add random number and random string patterns |
| 🇨🇳 Chinese | 新增了两种序列号生成规则：定长随机数字和随机字符串|

### Docs

| Language   | Link |
| ---------- | --------- |
| 🇺🇸 English |      |
| 🇨🇳 Chinese |    |

### Checklists
- [x] All changes have been self-tested and work as expected
- [x] Test cases are updated/provided or not needed
- [x] Doc is updated/provided or not needed
- [x] Component demo is updated/provided or not needed
- [x] Changelog is provided or not needed
- [x] Request a code review if it is necessary

2024-12-27 07:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=5959) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=5959) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mytharcher<br/>:x: kennnnnnnnnn<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=5959) it.</sub>

2025-01-06 06:30 UTC, mytharcher commented
感谢贡献！

从功能的角度考虑，两条规则本质都是随机字符，可以合并成一条，称为“随机字符”，并通过配置项区选择字符集以及 padding 规则，例如：

* 字符集（多选）：数字、字母（大小写）、符号等
* 补位规则：在前补充、在后补充，以及补位字符

2025-01-06 06:32 UTC, mytharcher requested changes
感谢贡献！

从功能的角度考虑，两条规则本质都是随机字符，可以合并成一条，称为“随机字符”，并通过配置项区选择字符集以及 padding 规则，例如：

* 字符集（多选）：数字、字母（大小写）、符号等

2025-01-10 07:39 UTC, kennnnnnnnnn reviewed
<img width="713" alt="image" src="https://github.com/user-attachments/assets/295bb3b2-8e48-4657-9a13-2e038b6380da" />
<img width="812" alt="image" src="https://github.com/user-attachments/assets/cae5fb0e-feec-48fa-ac31-7c60ded9be9e" />
统一了随机字符，增加了字符集验证，优化了随机生成方式

2025-01-11 04:03 UTC, kennnnnnnnnn commented
> 感谢贡献！
> 
> 从功能的角度考虑，两条规则本质都是随机字符，可以合并成一条，称为“随机字符”，并通过配置项区选择字符集以及 padding 规则，例如：
> 
> * 字符集（多选）：数字、字母（大小写）、符号等

处理了

2025-01-11 04:11 UTC, mytharcher requested changes

2025-01-11 04:11 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-field-sequence/src/client/sequence.tsx
> +      paddingType: {
这个选项其实没有必要了，因为都是固定长度的。

2025-01-11 04:11 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-field-sequence/src/server/fields/sequence-field.ts
> +  getMatcher(options: RandomCharOptions) {
这个逻辑需要增加一些测试用例来确保没有问题。

2025-01-14 02:31 UTC, mytharcher commented on packages/plugins/@nocobase/plugin-field-sequence/src/client/sequence.tsx
> +      paddingType: {
因为规则名称叫随机字符串，数字只是字符的一种，填 6 个随机数字，已经和补零没关系了，无论是 000123 还是 123000 都是随机生成。

2025-01-21 08:59 UTC, kennnnnnnnnn reviewed
去掉了多余的padding

2025-01-23 09:33 UTC, mytharcher approved these changes

2025-01-23 09:33 UTC, merged