fix: dragging an element to the left, right, or bottom would cause the element to disappear
nocobase/nocobase pull request #620
Opened 2022-07-12 11:27 UTC by Dunqing

releated issue: #383

fix second bug

2022-07-12 12:47 UTC, chenos requested changes
dnd-context 是核心抽象的组件，业务逻辑不适合写在这里

dn 的相邻位置移动的 api 还提供了一个 breakRemoveOn 参数，这个是用来处理递归删除的问题，如下面测试用例

https://github.com/nocobase/nocobase/blob/5f9d5436e74b6e1f9e838444144ff73ebfc766fd/packages/core/client/src/schema-component/hooks/__tests__/designable.test.ts#L244

Grid 的拖拽布局的问题在这个组件里，加上 breakRemoveOn 的逻辑就可以了，我提交了个 PR

https://github.com/nocobase/nocobase/pull/621/files

2022-07-13 00:23 UTC, Dunqing commented
我测试了下，拖动到自己下方依然会消失，刷新后会出现。

### 个人意见

我认为这种处理方式不是那么的好，会造成性能浪费。当一个 `element` 拖动到该 `element` 的上下左右方向应该都是无效的，因为位置没有改变。但你的改动依然会导致接口请求，浪费性能。

2022-07-13 04:57 UTC, chenos commented
> 我测试了下，拖动到自己下方依然会消失，刷新后会出现。
> 
> ### 个人意见
> 我认为这种处理方式不是那么的好，会造成性能浪费。当一个 `element` 拖动到该 `element` 的上下左右方向应该都是无效的，因为位置没有改变。但你的改动依然会导致接口请求，性能浪费。

赞同，消失的问题修复了，不过性能浪费的还没有优化，问题记录在 https://github.com/nocobase/nocobase/issues/625 issue 里了，有没有什么好的改进建议？

2022-07-13 05:23 UTC, Dunqing commented
> 赞同，消失的问题修复了，不过性能浪费的还没有优化，问题记录在 #625 issue 里了，有没有什么好的改进建议？

我这个 PR 的改动就避免了调用接口

### 目前想到的两个方案
1. 按照目前的情况，应该提供一个新的 `callback` 去处理

比如

```ts
const beforeInsert = active?.data?.current?.beforeInsert || () => {};

if (beforeInsert(activeSchema, endSchema)) {
    return props?.onDragEnd?.(event);
}
``` 

2. 当 `自己` 拖拽时隐藏自己的`Dropable`。

> RowDivider 和 CowDivider 都不渲染

2022-07-13 05:29 UTC, Dunqing commented
第二种方案我感觉会好些，因为从页面效果来看就能体现出该`Element`是不能拖动到属于它的的区域

2022-07-13 06:39 UTC, chenos commented
> 第二种方案我感觉会好些，因为从页面效果来看就能体现出该`Element`是不能拖动到属于它的的区域

感觉可以，直接通过 css 隐藏比较合适，也不会有高亮了。你那边能直接修改再提交么？改好了，再 merge。

拖拽区块时，区块 draging 时：

- 一行一列一区块时，相邻的 RowDivider、ColDivider 隐藏
- 一行多列一区块时，相邻的 ColDivider 隐藏，RowDivider 不隐藏
- 如果列里有多个区块时，相邻的 RowDivider、ColDivider 不隐藏

2022-07-14 04:52 UTC, Dunqing commented
> 感觉可以，直接通过 css 隐藏比较合适，也不会有高亮了。你那边能直接修改再提交么？改好了，再 merge。

直接 css 隐藏会导致布局变化，改成了不传 setNodeRef

> 拖拽区块时，区块 draging 时：
> 
> * 一行一列一区块时，相邻的 RowDivider、ColDivider 隐藏
> * 一行多列一区块时，相邻的 ColDivider 隐藏，RowDivider 不隐藏
> * 如果列里有多个区块时，相邻的 RowDivider、ColDivider 不隐藏

已实现

2022-07-15 00:19 UTC, Dunqing commented
> 录了个视频
> 
>  3gwi8.mp4

已处理

2022-07-15 02:39 UTC, merged