Feature/export
nocobase/nocobase pull request #73
Opened 2021-04-07 13:45 UTC by mytharcher

初步实现了在列表视图将数据导出为 excel（.xlsx）的功能，主要逻辑复用原有的 list action。大部分字段类型均以人类用户可以理解的字面值导出，暂时还有一些缺陷如下：

1. 默认不导出开发者模式为 `true` 的字段，且一些反向关联产生的字段暂未去除（操作日志、看板分组等）。
2. 子表格因暂时还没有 `labelField` 的定义，暂时以选项 id 导出。
3. 暂时未添加导出时的字段选择相关交互。

2021-04-08 06:11 UTC, chenos requested changes

2021-04-08 06:11 UTC, chenos commented on packages/plugin-export/src/actions/export.ts
> +    const { title, fields } = table.getOptions();
fields 需要有排序

2021-04-08 06:11 UTC, chenos commented on packages/plugin-export/src/actions/export.ts
> +  await actions.common.list(ctx, async () => {
export 复用了 list，权限也直接继承？

2021-04-08 06:11 UTC, chenos commented on packages/plugin-export/src/actions/export.ts
> +        fields.map(field => field.title),
导出哪些字段可能由 request 提供，可以把后端参数部分的先弄好

2021-04-10 06:47 UTC, mytharcher commented
尝试了将插件移回核心库，但由于权限部分暂时没有办法实现“继承”的概念，会导致核心 action 依赖权限插件和 collections 插件，比较不合适。所以还是暂时作为独立插件。

2021-05-17 03:11 UTC, merged