工作流函数增加了部分功能
nocobase/nocobase pull request #741
Opened 2022-08-15 16:53 UTC by William-d-zk

修复了一些i18n的bug
工作流添加了2个基础函数。

2022-08-16 00:58 UTC, iannil commented
nice work

2022-08-17 14:40 UTC, mytharcher requested changes

2022-08-20 02:38 UTC, William-d-zk commented on packages/core/client/src/locale/zh_CN.ts
> +  "concat": "拼接",
OK

2022-08-20 03:04 UTC, William-d-zk commented on packages/core/client/src/schema-component/antd/color-select/ColorSelect.tsx
> +  geekblue: '{{t("Geek Blue")}}',
这不是命名的问题，antd和umi中引用的源标识 就是Geek Blue ，小写在中文环境下降就会无法正确的识别为"极客蓝"

2022-08-20 03:13 UTC, closed without merging

2022-08-20 03:57 UTC, mytharcher commented on packages/core/client/src/schema-component/antd/color-select/ColorSelect.tsx
> +  geekblue: '{{t("Geek Blue")}}',
根据目前统一的风格，这个情况应该将键名（key）也改成 `"Geek blue"`。