代码调整 & i18n 字典调整
nocobase/nocobase pull request #761
Opened 2022-08-20 03:18 UTC by William-d-zk

之前的pull request 的一些 问题修复，重新提交

2022-08-20 04:04 UTC, mytharcher commented
没有发现提交 [fdb3d1a](https://github.com/nocobase/nocobase/pull/761/commits/fdb3d1afa62ad0a409a0b3a0f4162188063e95b7) 中包含和 `padStart` 相关的内容。

其他大部分在 #741 中的问题还是存在，主要是 `format_number_concat` 不是一个针对通用场景的计算方法，如果有需要建议在具体的 app 中扩展，但通用的计算函数不会接受这个需求。

另外建议在同一个需求的修改都沿用同一个 PR，没必要关闭后重新发起新的。

2022-08-20 11:54 UTC, mytharcher requested changes
Need changes.

2022-08-21 03:45 UTC, William-d-zk commented
#741  是保持了和原有的代码字段一致。沿用了小写开头

2022-08-24 15:18 UTC, mytharcher requested changes
没有看到任何新的提交和有相关的文件变动。请确保你已将提交推送到正确的分支，且已学会使用 Github PR 相关功能。

2022-08-28 06:27 UTC, mytharcher requested changes
最主要的还是之前的问题，作为通用的计算函数，不会接受 `concatId` 这个专用的计算方法。如果一定要加这个函数，请在具体项目的 app 中自行扩展，但公共库不会接受这个 feature。如果坚持提交这个方法，PR 会被关闭。

2022-09-08 03:10 UTC, closed without merging