feat: add user-groups plugin
nocobase/nocobase pull request #765
Opened 2022-08-21 14:36 UTC by songyx

fixed the code reviews opinions.add new plugin usergroups.
1.add collections usergroups. usergroups m2m users. usergroups o2m usergroups.
2.with a db hook,new users will be add to the default usergroups.
3.need to be plug in before users.

install:
if you have installed.you need insatll again.
yarn nocobase install -f.
it will create new tables:usergroups,usergroupsUsers

2022-09-06 14:51 UTC, mytharcher requested changes

2022-09-06 14:51 UTC, mytharcher commented on packages/plugins/user-groups/src/__tests__/userGroupsRepository.getSubGroupTree.test.ts
> +        const subTrees = await userGroupRepository.getSubGroupTree(gid, true);
不提供 gid 在这种情况下可以认为是一个错误的输入，throw error 更合适，类似函数参数校验。

2022-09-06 14:51 UTC, mytharcher commented on packages/plugins/user-groups/src/repository/userGroupRepository.ts
> +     * @param ctx
注释参数不匹配。

2022-09-06 14:51 UTC, mytharcher commented on packages/plugins/user-groups/src/repository/userGroupRepository.ts
> +            for (let td of childrens) {
可以用 children.map() 改写。

2022-09-06 14:51 UTC, mytharcher commented on packages/plugins/user-groups/src/repository/userGroupRepository.ts
> +            for (let td of childrens) {
可以用 children.map() 改写。

2022-09-06 14:51 UTC, mytharcher commented on packages/plugins/user-groups/src/repository/userGroupRepository.ts
> +        const childrens = await this.find({
typo: childrens -> children

2022-09-06 14:51 UTC, mytharcher commented on packages/plugins/user-groups/src/repository/userGroupRepository.ts
> +    async getSubGroupTree(gid: string, noTree = false) {
noTree 可以改为 plain，更容易理解。

另外甚至可以改成两个函数，因为返回值类型都不同。

2022-09-06 14:51 UTC, mytharcher commented on packages/plugins/user-groups/src/repository/userRepository.ts
> +export class UserRepository extends Repository {
在一个依赖 plugin-users 插件的插件里定义被依赖插件管理的表的 repository 有风险，如果未来 users 插件自身再定义了同名的 repository，会有冲突的问题。

后面在 users 插件里使用这个由不是自身定义的 repository 也会有问题。

如果实在无法解除循环依赖，有可能考虑两个插件需要合并。

2022-09-06 14:51 UTC, mytharcher commented on packages/plugins/user-groups/src/repository/userGroupRepository.ts
> +            if (!tp['roles']) {
理论上加了 appends 的多对多关联查询，都自动会返回一个数组，最多就是这个数组为空，但不会不存在，所以这个判断可能没有必要。

2022-09-08 02:53 UTC, chenos requested changes

2022-10-23 11:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=765) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=765) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=765) it.</sub>

2023-03-31 02:10 UTC, closed without merging