Feat/plugin import 2
nocobase/nocobase pull request #792
Opened 2022-09-01 05:44 UTC by chenos

2022-09-02 03:31 UTC, mytharcher requested changes
另外 server 端最好加一下测试用例，至少可以描述正常的行为。

2022-09-02 03:31 UTC, mytharcher commented on packages/plugins/import/src/server/actions/importXlsx.ts
> +    ctx.body = {
这个返回结构是否考虑和 data-wrapping 结合下，result 部分放到 meta 里？

2022-09-12 12:18 UTC, chenos commented on packages/plugins/import/src/server/utils/transform.ts
> +  return value === '是' ? 1 : null;
需要考虑多语言？

2022-09-12 12:19 UTC, chenos commented on packages/plugins/import/src/server/utils/transform.ts
> +  return item?.value;
如果导入时直接提供的就是 value，也是可以直接存的？

2022-09-12 12:20 UTC, chenos commented on packages/plugins/import/src/server/utils/transform.ts
> +  const results = values.map((val) => enumData.find((item) => item.label === val));
find 找不到的怎么处理？

2022-09-12 12:22 UTC, chenos commented on packages/plugins/import/src/server/utils/index.ts
> +    set(newRecord, dataIndex[0], await t({ ctx, column, value: cell, field }));
这个 set 看起来有问题，应该是完整路径？如果同时存在：
- assoc.key1
- assoc.key2
会有遗漏？

2022-09-12 12:41 UTC, chenos commented on packages/plugins/import/src/server/actions/importXlsx.ts
> +          failureData.unshift(failData);
fail data 应该是原数据，现在这样可能不是

2022-09-12 12:48 UTC, chenos commented on packages/plugins/import/src/server/middleware/index.ts
> +  const upload = multer().single('file');
仅在 `importXlsx` 里有效

2022-09-12 13:48 UTC, semmywong commented on packages/plugins/import/src/server/actions/downloadXlsxTemplate.ts
> +export async function downloadXlsxTemplate(ctx: Context, next: Next) {
这部分之前设计的时候与陈霖沟通过，我本身意见也是偏于在前端实现，但是陈霖的意思有两方面的原因：1、前端去实现操作下载Excel下载或解析，需要引入第三方库，过于笨重，没有必要，前端纯粹点请求下载就可以；2、目前市面上主流低代码平台，这部分模板下载也是在服务端实现的。

2022-09-12 13:51 UTC, semmywong commented on packages/plugins/import/src/server/actions/importXlsx.ts
> +const IMPORT_LIMIT_COUNT = 10000;
文件大小我记得是放在前端进行限制。

2022-09-12 13:53 UTC, semmywong commented on packages/plugins/import/src/server/actions/importXlsx.ts
> +  const failureData = list.splice(IMPORT_LIMIT_COUNT + 1);
这个splice没有错，需要改变list变量，我需要把list变量保证只有IMPORT_LIMIT_COUNT + 1行数据(1表示表头)

2022-09-12 13:56 UTC, semmywong commented on packages/plugins/import/src/server/actions/importXlsx.ts
> +      await Promise.allSettled<any>(
这边确实有性能问题，性能测试也缺失。具体性能改进，可以再探讨，提前返回202有个问题，如果有导入失败的数据的时候，比较麻烦，没办法再次返回。

2022-09-12 13:57 UTC, semmywong commented on packages/plugins/import/src/server/utils/transform.ts
> +  return `${value}`;
这边null 或undefiend可能需要抛出异常

2022-09-12 13:58 UTC, semmywong commented on packages/plugins/import/src/server/utils/transform.ts
> +  const { dataIndex, enum: enumData } = column;
有关系的，不知道你是否还记得我上次截图给你，那个o2o关联表，显示出来的是key值，不是具体的lable值

2022-09-13 06:05 UTC, semmywong commented on packages/plugins/import/src/server/actions/importXlsx.ts
> +    ctx.body = {
已更改

2022-09-13 06:06 UTC, semmywong commented on packages/plugins/import/src/server/utils/transform.ts
> +  return `${value}`;
已更改

2022-09-13 06:08 UTC, semmywong commented on packages/plugins/import/src/server/utils/transform.ts
> +    return numberValue / 100;
已更改

2022-09-13 06:09 UTC, semmywong commented on packages/plugins/import/src/server/utils/transform.ts
> +  return value === '是' ? 1 : null;
已更改

2022-09-13 06:11 UTC, semmywong commented on packages/plugins/import/src/server/utils/transform.ts
> +  return item?.value;
这里个人感觉用户导入只会导入label，不会直接输入value去导入，就像不会输入ID一样，且这里也最好统一只对label的处理，再判断是否是value值，容易混乱

2022-09-13 06:42 UTC, semmywong commented on packages/plugins/import/src/server/middleware/index.ts
> +  const upload = multer().single('file');
已更改

2022-09-13 06:43 UTC, semmywong commented on packages/plugins/import/src/server/actions/importXlsx.ts
> +          failureData.unshift(failData);
已更改

2022-09-13 06:44 UTC, semmywong commented on packages/plugins/import/src/server/utils/transform.ts
> +  const results = values.map((val) => enumData.find((item) => item.label === val));
找不到抛异常，不导入该条数据

2022-10-23 11:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nocobase/nocobase?pullRequest=792) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nocobase/nocobase?pullRequest=792) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: chenos<br/>:x: semmywong<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nocobase/nocobase?pullRequest=792) it.</sub>

2022-10-28 11:39 UTC, closed without merging