Perf/cache schema
nocobase/nocobase pull request #877
Opened 2022-10-05 04:47 UTC by lyf-coder

base on #876

2022-10-10 11:29 UTC, chareice commented
1. 缓存名直接用x-uid 可能导致缓存名称冲突，致后期可能存在难以排查的问题。
2. 读写层次设计不一致， 在 repository 层进行了缓存清除，但是缓存的写入却是在 action 层处理，
3. actions 中的缓存判断破坏开闭原则，在callRepositoryMethod中的 if 语句应当被替换为更好的设计实现。

如果我来实现的话，我可能会在 repository 的 getJsonSchema 和 getProperties 函数增加 一个 readFromCache: bool 的参数，为 true 的话，则尝试从缓存读取数据，当前情况在 actions 中的调用，传递 true 。这样可以保持读写设计的层次一致，并且不破坏 actions 中的开闭设计。

2022-10-10 11:42 UTC, chareice reviewed
1. 缓存名直接用x-uid 可能导致缓存名称冲突，致后期可能存在难以排查的问题。
1. 读写层次设计不一致， 在 repository 层进行了缓存清除，但是缓存的写入却是在 action 层处理，
1. actions 中的缓存判断破坏开闭原则，在callRepositoryMethod中的 if 语句应当被替换为更好的设计实现。
如果我来实现的话，我可能会在 repository 的 getJsonSchema 和 getProperties 函数增加 一个 readFromCache: bool 的参数，为 true 的话，则尝试从缓存读取数据，当前情况在 actions 中的调用，传递 true 。这样可以保持读写设计的层次一致，并且不破坏 actions 中的开闭设计。

2022-10-10 11:42 UTC, chareice commented on packages/plugins/ui-schema-storage/src/actions/ui-schema-action.ts
> +    return ctx.cache.wrap(params, func);
缓存名直接用 x-uid 是否会与其他类型缓存存在名称冲突的可能，有无增加 prefix 的必要？

2022-10-10 11:42 UTC, chareice commented on packages/plugins/ui-schema-storage/src/actions/ui-schema-action.ts
> +      returnValue = await cacheMethods[method](ctx, params, options, () => {
actions 中的缓存判断破坏开闭原则，在callRepositoryMethod中的 if 语句应当被替换为更好的设计实现。

2022-10-10 11:42 UTC, chareice commented on packages/plugins/ui-schema-storage/src/repository.ts
> +  async clearXUidPathCache(xUid: string, transaction: Transaction) {
读写层次设计不一致， 在 repository 层进行了缓存清除，但是缓存的写入却是在 action 层处理，

2022-10-11 10:19 UTC, lyf-coder commented on packages/plugins/ui-schema-storage/src/repository.ts
> +  async clearXUidPathCache(xUid: string, transaction: Transaction) {
已从action移到repository层处理读缓存

2022-10-11 10:27 UTC, lyf-coder commented on packages/plugins/ui-schema-storage/src/actions/ui-schema-action.ts
> +    return ctx.cache.wrap(params, func);
这个问题在使用缓存的地方都存在，token优化的那个分支开始也对userId作为key进行了前缀包装，后面又去掉了，主要是各自处理不规范，仍然有冲突的很大可能。所以应该从缓存入手，需要对缓存模块进行进一步设计，分组缓存？或者插件缓存？希望能达到的目标是，在尽量不增加key的长度情况下，避免缓存冲突问题。暂时先不在此考虑缓存冲突问题

2022-10-12 10:19 UTC, chareice commented on packages/plugins/ui-schema-storage/src/actions/ui-schema-action.ts
> +    return ctx.cache.wrap(params, func);
暂时不处理的话也行，之后遇到问题再处理。

2022-10-13 00:23 UTC, lyf-coder commented on packages/plugins/ui-schema-storage/src/actions/ui-schema-action.ts
> +    return ctx.cache.wrap(params, func);
👌

2022-10-22 11:26 UTC, chenos requested changes
既然提供了 readFromCache，那是不是不仅要测 true, false 的情况也要有个用例。

其他一些用例（重点测试子节点变更了，取父节点树时子节点是否更新了）：
A->B->C，修改 C 参数，取 A 树，子节点 C 参数已修改
A->B，在 B 节点后新增 C，取 A 树，结果为 A->B->C
A->B->C/A->D 移动 C 到 D 后面，取 A 树，结果为 A->B/A->D->C
A->B->C/D->E 移动 C 到 E 后面，取 A 树，结果为 A->B，取 D 树，结果为 D->E->C

2022-10-24 01:13 UTC, merged