Perf/token
nocobase/nocobase pull request #878
Opened 2022-10-05 16:07 UTC by lyf-coder

base on #876 
token add user's roleNames and remove ctx.state.currentUser,set ctx.state.currentUserId

2022-10-08 11:19 UTC, mytharcher requested changes

2022-10-08 11:19 UTC, mytharcher commented on packages/plugins/users/src/util.ts
> +  LOGOUT = -1,
如果是描述状态，可以用形容词 `LOGGED_OUT` / `EXPIRED`。

2022-10-09 01:32 UTC, lyf-coder commented on packages/plugins/users/src/util.ts
> +  LOGIN = 1,
* 缓存有丢失的可能，黑名单机制下，假如缓存失效（重启等），那么就丢失了黑名单状态，token正常校验，可能会有一些不合理的状况出现。
* 目前的情况更像是白名单，有则通过，无则强制重新登录以保证不会出现失效状态的token情况，另外不同状态可以进行不同的处理对前端进行提示（提示这块目前并未实现）。
* 假如可以容忍一定的可能性（token内的角色被移除了，但是token没失效，然后在未失效的时候服务器重启绕过验证，然后以过期的角色进行一些操作，此可能行非常小，但存在），那么可用黑名单机制节省掉很多token状态缓存。

2022-10-09 01:32 UTC, lyf-coder commented on packages/plugins/users/src/actions/users.ts
> +  appends.push('roles');
👌

2022-10-09 01:32 UTC, lyf-coder commented on packages/plugins/users/src/actions/users.ts
> +    const token = jwtService.sign({ userId: user.id, roleNames });
👌

2022-10-09 02:17 UTC, mytharcher commented on packages/plugins/users/src/util.ts
> +  LOGIN = 1,
那现在白名单机制是不是也会造成重启后状态丢失，客户端即使 token 有效，也会被要求重新登录？

2022-10-09 02:44 UTC, lyf-coder commented on packages/plugins/users/src/util.ts
> +  LOGIN = 1,
是的，但能保证业务安全。假如不想影响用户体验，可在token有效，但无法获取到token是登录状态时，重新生成token更新客户端的token,然后服务端token状态设置为登录。对于token有效，且token缓存中状态是数据过期的情况也可如此，对用户体验没有影响，完成续租token。

2022-10-09 02:49 UTC, mytharcher commented on packages/plugins/users/src/util.ts
> +  LOGIN = 1,
> 可在token有效，但无法获取到token是登录状态时，重新生成token更新客户端的token,然后服务端token状态设置为登录。

这个也存在问题，如果重启以后缓存丢失了，如何按之前的逻辑判断用户端的 token 是否在黑名单呢？相当于黑名单也丢失了，用户的 token 在 JWT 层面是有效的，重启后访问就被下发了登录状态的新 token 并放入缓存，这个逻辑就冲突了。

2022-10-09 02:58 UTC, lyf-coder commented on packages/plugins/users/src/util.ts
> +  LOGIN = 1,
没有影响的，token状态是用userId作为key记录的，当重启后token解析有效，但是根据userId获取不到缓存中的状态（正常缓存中肯定要有一个状态-登录/退出/过期等），这时候重新生成新的token，然后设置该用户的缓存状态为登录。并不关心是不是黑名单里的（毕竟这个黑名单主要是保证token中的用户数据是有效最新的-新token肯定是最新的了）

2022-10-09 04:05 UTC, mytharcher commented on packages/plugins/users/src/util.ts
> +  LOGIN = 1,
感觉对黑名单的理解可能不太一致。如果按照现有逻辑，用户在 signout 操作的时候会将 userId 映射到 LOGGED_OUT，同时客户端还保留旧的 token，那如果继续用这个旧 token 请求资源，parseToken 基于缓存无法认证该用户（在 ctx 添加 currentUserId），这是正常逻辑。

但是当用户使用旧 token 请求资源之前，服务端重启了，重启之后旧 token 理论上会被认为有效（不在黑名单），这里再加入签发新 token 给用户，并添加到缓存中，是不是就相当于本该被认为失效的旧 token 在服务端重启后仍然可以获得认证并操作？那这样黑名单的用意就有漏洞了，如果是被泄露的 token，在这种时候用户即使知道，主动先登出再重新登入换了更新的 token，但是重启之前的旧 token 由于是基于 userId 映射的有效性，就仍被认为有效，这是不是也会有安全问题？

所以我不太清楚这个黑名单的逻辑是不是为了处理用户主动使 token 失效这种场景（比如登出），如果是的话，那这里有漏洞。是不是可以考虑用 token 作为键直接进行缓存，以作为白名单或黑名单使用更合理（而且这个场景还要考虑缓存的持久化才更完备）？

如果不是为了主动失效，那在 signout 时设置缓存为 LOGGED_OUT 就不太理解用意是什么了。

2022-10-09 04:26 UTC, lyf-coder commented on packages/plugins/users/src/util.ts
> +  LOGIN = 1,
* 正常用户，登出后不会有旧token访问的情况，因为客户端会清除。
* 重新给发token的情况的确会有你所说的问题，这里重新的实现并未处理token泄漏的问题，而是在原有的设计之上实现的设计优化问题。这里添加token状态位只是为了保证token中信息的有效性，设置 LOGGED_OUT，也只是当拦截退出状态的token请求，比原来会提高一定的安全性，并非是为了完全保证安全性。
* 可以仍然使用原来token，即只保存一个userId，然后在服务端缓存每个用户的角色信息。然后更新用户角色信息的缓存也可以。那样多消耗一些缓存而已。只不过当时实现时选择了目前的方案，角色信息放入到token中，而一旦放入，就要考虑该信息的有效性，所以设置了此状态位。
* token泄漏的安全问题需要另外的设计，并未在本次的实现中进行考虑和设计

2022-10-09 04:40 UTC, mytharcher commented on packages/plugins/users/src/util.ts
> +  LOGIN = 1,
基本理解了，主要是为了保证 role 的有效性，顺带稍微提高了一些登出的安全性。对于完整的安全性来说，仍然是一个过渡版本。

LGTM

2022-10-11 01:02 UTC, lyf-coder commented on packages/plugins/users/src/actions/users.ts
> +  appends.push('roles');
这里通过在 `acl` 的 `setCurrentRole` 中间件中设置 `ctx.state.currentUserAppends` 完成重构，已提交更改

2023-12-17 08:49 UTC, closed without merging